process-analytics/bpmn-visualization-js

.eslintignore
In particular, ignore the `node_modules` directory
=> Add eslintignore

package.json, src/component/mxgraph/MxGraphConfigurator.ts, src/component/parser/json/BpmnJsonParser.ts, src/component/parser/json/converter/AbstractConverter.ts, src/component/parser/json/converter/EdgeConverter.ts, src/component/parser/json/converter/EdgeModelConverter.ts, src/component/parser/json/converter/ShapeConverter.ts, src/component/parser/json/converter/ShapeModelConverter.ts, src/config/main.ts, test/component/parser/xml/BpmnXmlParser.test.ts
The github build workflow now disallows eslint warnings to avoid new additions.
Fix existing warnings.
=> [INFRA] lint-check: fail on warnings + fix warnings

test/component/parser/xml/BpmnXmlParser.test.ts
This has not been detected during review of #57 
Also renamed a test which was referencing `user tasks` instead of `sequence flows`
=> [TEST] sequence flows xml parsing: remove extra console logs

docs/bpmn-support-how-to.adoc, src/component/parser/json/converter/ShapeModelConverter.ts, src/model/bpmn/shape/ShapeBpmnElementKind.ts
This change will simplify work to do to support new BPMN element types.
Previously, we had to modify the `ShapeModelConverter` in addition to the `ShapeBpmnElementKind` enum. The enum change is mandatory because this is how we identify the element for rendering.
But having to change the converter was a pain and led to code duplication.
The converter now generically considers all elements of the enum to apply the conversion. The BPMN containers (lane for instance) are still managed manually as they require a dedicated processing.
Also introduce a new doc which explains briefly how to support a new BPMN element type.
=> Refactor: detection based on ShapeBpmnElementKind enum only

src/component/parser/json/BpmnJsonParser.ts, src/component/parser/json/JsonParser.ts, src/component/parser/json/converter/DiagramConverter.ts, src/component/parser/json/converter/SemanticConverter.ts
Move jsonConvert configuration in a singleton in order to not duplicate instantiation & configuration
=> Refactor: jsonConvert as singleton

package.json
This was causing a npm warning
npm WARN bpmn-visu-js@0.1.0 license should be a valid SPDX license expression
=> [INFRA] fix license declaration in package.json

src/component/parser/json/Definitions.ts, src/component/parser/json/converter/ProcessConverter.ts
The content of the Process is never used, as parsing the Process is only
required to fill the data structure used by `DiagramConverter` to create the
final BpmnModel
So we kept useless data during the parsing.
Closes #125
=> Refactor: the Json Parser Process object is now an empty type

.github/workflows/build.yml
They are generating false positives because of jest timeout.
This currently makes all commits marked as 'build failed' so until we fix the
issue, disable the tests.
Covers #154
=> [INFRA] build gh workflow: temporarily disable e2e tests

.github/workflows/build.yml, test/e2e/View.test.ts
https://docs.npmjs.com/cli/ci documentation
This command is similar to npm-install, except it’s meant to be used in
automated environments such as test platforms, continuous integration, and
deployment.
=> [INFRA] build gh wf: use 'npm ci' instead of 'npm install'

src/component/BpmnVisu.ts, src/component/mxgraph/MxGraphRenderer.ts, src/component/mxgraph/ShapeConfigurator.ts
Use `typeof` when retrieving types from `MxGraphFactoryService`
- BpmnVisu: add type to mxClient and mxUtils
- MxGraphRenderer: add type to mxPoint
- ShapeConfigurator: update todo about 'mxSvgCanvas2D'
=> [REFACTOR] use mxgraph types instead of any

CONTRIBUTING.md
It was previously referred to Mocha which is not used anymore.
Closes #152
=> [DOC] explain jest usage in the contributing guide

.github/workflows/build.yml, .github/workflows/generate-documentation.yml
- run on push to master and pull_request
- always upload the generate documentation as artifact. On PR, this helps to
have a doc preview
- when the workflow is triggered by a `push to master`, push the generated
documentation to the `gh-pages` branch
Covers #138
**Notes**:
- The GitHub Pages push (run only after a push to the master branch) has been tested in a [playground/demo repository](https://github.com/tbouffard/playground-release-drafter-and-gh-pages/commit/6f55a7850263e66c96c1cf51d0d51f0e57d05764)
- Documentation preview for PR will be managed later, see #180
=> [INFRA] add a GH Workflow to build and publish documentation

docs/bpmn-support.adoc, src/component/mxgraph/MxGraphRenderer.ts, src/component/mxgraph/StyleConfigurator.ts, src/component/mxgraph/shape/EndEventShape.ts, test/e2e/View.test.ts
Introduce a new way of managing EndEvent shapes
- when creating a vertex, set the event type as part of the style
- the event type style information are used by the Event shape to display the
related event icon
To prepare StartEvent shapes to act in the same way, a top level Event shape
already manages some parts of the rendering.
This simplifies style declaration: there is no need to define a new style each
time we want to support a new event type nor update anything else.
Our custom mxGraph Renderer will always add the event type to the style
associated to the vertex.
Thanks to that, any new supported event type will be rendered as a None Event by
default.
closes #137
=> [FEAT] render terminate end event

CONTRIBUTING.md, README.md, docs/architecture/00-index.adoc
We decided to put most of development information in this guide, not in the
README.
The release part of the contributing guide was wrong whereas it was correct in
the README which was confusing.
Also add contributing guide and doc site development section cross links for a
better navigation and understanding.
=> [DOC] move all development info to the contributing guide

docs/bpmn-support-roadmap.adoc, docs/bpmn-support.adoc, docs/index.adoc
- toc: only display 2 levels. Previously, it was set to '5' which is too much
for now as we do not have a lot of content
- set numeration also on deep sections. We previously stopped at 2, so
sections like 'XML Parser' were un-numerated
- fix title of sections about 'BPMN Support'. Previous wording was too long
and contained useless words (' Description of the')
- supported BPMN elements: remove 'page' words. Even if the AsciiDoctor source
is in a single file/page, it is intended to be included in a single html doc,
so 'page' is not accurate here.
=> [DOC] improve html rendering

docs/bpmn-support.adoc, src/component/mxgraph/ShapeConfigurator.ts, src/component/mxgraph/StyleConfigurator.ts, src/component/mxgraph/shape/task-shapes.ts, src/service/MxGraphFactoryService.ts, test/e2e/View.test.ts
=> [FEAT] Render Task

docs/bpmn-support.adoc, src/component/mxgraph/ShapeConfigurator.ts, src/component/mxgraph/StyleConfigurator.ts, src/component/mxgraph/shape/gateway-shapes.ts, src/model/bpmn/shape/ShapeUtil.ts, src/service/MxGraphFactoryService.ts
=> [FEAT] Render Exclusive Gateway

README.md, docs/bpmn-support.adoc, src/component/mxgraph/ShapeConfigurator.ts, src/component/mxgraph/StyleConfigurator.ts, src/component/mxgraph/extension/MxScaleFactorCanvas.ts, src/component/mxgraph/shape/task-shapes.ts, src/model/bpmn/shape/ShapeUtil.ts, test/e2e/View.test.ts, test/unit/model/bpmn/shape/ShapeUtil.test.ts
=> [FEAT] Render Service task

README.md, docs/architecture/bpmn-support-how-to.adoc, docs/bpmn-support.adoc, src/component/mxgraph/ShapeConfigurator.ts, src/component/mxgraph/StyleConfigurator.ts, src/component/mxgraph/extension/MxScaleFactorCanvas.ts, src/component/mxgraph/shape/task-shapes.ts, test/e2e/View.test.ts
This PR introduces the rendering of the `User Task` and add an icon based on the [person octicons](https://primer.style/octicons/person). Please note that this icon may not be the final one and may be replaced in the future.
In addition, the following internals are updated or added as part of this PR:
- generalize tasks rendering
- introduce an easy way to render icon whatever its original size (scale factor tooling)
- integration of a SVG based icon into the lib
- usage of the [mxgraph-svg2shape](https://github.com/process-analytics/mxgraph-svg2shape) / [svg2xml](https://github.com/jgraph/svg2xml) tools to simplify the SVG icon integration and to collect issue feedbacks
Closes #143
=> [FEAT] render user task

docs/bpmn-support.adoc, src/component/mxgraph/ShapeConfigurator.ts, src/component/mxgraph/StyleConfigurator.ts, src/component/mxgraph/shape/gateway-shapes.ts
=> [FEAT] render parallel gateway

docs/bpmn-support-roadmap.adoc, docs/bpmn-support.adoc, src/component/mxgraph/ShapeConfigurator.ts, src/component/mxgraph/shape/event-shapes.ts, src/model/bpmn/shape/ShapeBpmnElementKind.ts, test/e2e/View.test.ts, test/unit/component/parser/json/BpmnJsonParser.event.intermediate.catch.timer.test.ts
The shape is identified as an intermediate catch event (rounded, double thin line). As for the timer start event, we currently do not render the final icon, but the 2 events are identified in the same way (filled in green)
Event | Render
------------ | -------------
timer start event | ![image](https://user-images.githubusercontent.com/27200110/80762367-b8073480-8b3c-11ea-8d85-3fd0b71a68ba.png)
timer intermediate catch event | ![image](https://user-images.githubusercontent.com/27200110/80762014-f4866080-8b3b-11ea-9ef4-baf0bf3971b5.png)
Closes #89
=> [FEAT] display timer intermediate catch event

src/component/mxgraph/StyleConfigurator.ts, src/component/mxgraph/extension/MxScaleFactorCanvas.ts, src/component/mxgraph/shape/gateway-shapes.ts
=> [FEAT] improved rendering for exclusive gateway

CONTRIBUTING.md
We are not documenting changes in a changelog file but we use GitHub releases instead.
So remove the need of updating a changelog when contributing.
Closes #131
=> [DOC] remove reference to changelog file

docs/bpmn-support.adoc, src/component/mxgraph/shape/event-shapes.ts, test/e2e/View.test.ts
=> [FEAT] Render Catch Message Intermediate Event

docs/bpmn-support.adoc, src/component/mxgraph/StyleConfigurator.ts, src/model/bpmn/shape/ShapeBpmnElementKind.ts, test/unit/component/parser/json/BpmnJsonParser.gateway.inclusive.test.ts
=> [FEAT] Display inclusive gateway

docs/bpmn-support.adoc, src/component/mxgraph/shape/event-shapes.ts, test/e2e/View.test.ts
=> [FEAT] Render Message End Event

src/component/mxgraph/ShapeConfigurator.ts, src/component/mxgraph/StyleConfigurator.ts, src/component/mxgraph/shape/gateway-shapes.ts, test/e2e/View.test.ts
=> [FEAT] Render inclusive gateway

CONTRIBUTING.md, jest-puppeteer.config.js, test/e2e/mxGraph.model.test.ts, test/e2e/mxGraph.view.test.ts
This first tests check that the following BPMN elements are rendered as SVG
shape on the document
- start and events as ellipse
- task as rectangle
In addition
- mxGraph model tests are now in a dedicated file
- let disable the headless mode with environment variable
Notes
- this PR implements what we decided in https://github.com/process-analytics/bpmn-visualization-js/pull/150#issuecomment-624630574
- closes #48
=> [INFRA] introduce graph display end to end tests

docs/bpmn-support.adoc, src/component/mxgraph/StyleConfigurator.ts
=> [FEAT] Render Sequence Flow

docs/architecture/00-index.adoc, docs/architecture/architecture-overview.adoc, docs/architecture/bpmn-support-how-to.adoc, docs/architecture/images/architecture/architecture_overview.svg, docs/architecture/mxgraph-integration.adoc, docs/bpmn-support.adoc
=> [DOC] architecture additions

.github/release-drafter.yml, .github/workflows/build.yml, .github/workflows/fill-gh-draft-release.yml, .github/workflows/release-drafter.yml, CONTRIBUTING.md
Closes #251
**Notes**
- Testing: this is hard to do, I have done lot of testing with a [personal playground repository](https://github.com/tbouffard/playground-release-drafter-and-gh-pages)
- Current limitations
- categories assignment: not possible to ensure several labels are set to assign to a category --> we cannot have _enhancement + bpmn suppport_ and _enhancement + bpmn rendering_, so I setup a category for the whole _bpmn suppport_ and another one for _bpmn rendering_
=> [INFRA] release-drafter continuously update github draft release

package-lock.json, src/component/mxgraph/MxGraphConfigurator.ts, src/component/mxgraph/MxGraphRenderer.ts, src/component/mxgraph/StyleConfigurator.ts, test/e2e/mxGraph.model.test.ts
Closes #101 
(previously depended on #283 & https://github.com/process-analytics/ts-mxgraph/pull/1)
- The render when the font is define:
- The render when the font is NOT define:
=> [FEAT] Render the Label Font of a Shape

src/component/mxgraph/MxGraphRenderer.ts, test/unit/component/mxgraph/MxGraphRenderer.test.ts
Done when creating mxGraph elements.
Closes #287
**Previous implementation**
**With new implementation**
=> [FEAT] consider all Font attributes on rendering

test/unit/component/parser/json/BpmnJsonParser.call.activity.test.ts, test/unit/component/parser/json/BpmnJsonParser.event.end.message.test.ts, test/unit/component/parser/json/BpmnJsonParser.event.end.none.test.ts, test/unit/component/parser/json/BpmnJsonParser.event.end.terminate.test.ts, test/unit/component/parser/json/BpmnJsonParser.event.intermediate.catch.message.test.ts, test/unit/component/parser/json/BpmnJsonParser.event.intermediate.catch.timer.test.ts, test/unit/component/parser/json/BpmnJsonParser.event.intermediate.throw.message.test.ts, test/unit/component/parser/json/BpmnJsonParser.event.intermediate.throw.none.test.ts, test/unit/component/parser/json/BpmnJsonParser.event.start.message.test.ts, test/unit/component/parser/json/BpmnJsonParser.event.start.none.test.ts, test/unit/component/parser/json/BpmnJsonParser.event.start.timer.test.ts, test/unit/component/parser/json/BpmnJsonParser.gateway.exclusive.test.ts, test/unit/component/parser/json/BpmnJsonParser.gateway.inclusive.test.ts, test/unit/component/parser/json/BpmnJsonParser.gateway.parallel.test.ts, test/unit/component/parser/json/BpmnJsonParser.label.font.test.ts, test/unit/component/parser/json/BpmnJsonParser.lane.test.ts, test/unit/component/parser/json/BpmnJsonParser.process.test.ts, test/unit/component/parser/json/BpmnJsonParser.task.abstract.test.ts, test/unit/component/parser/json/BpmnJsonParser.task.receive.test.ts, test/unit/component/parser/json/BpmnJsonParser.task.service.test.ts, test/unit/component/parser/json/BpmnJsonParser.task.user.test.ts, test/unit/component/parser/json/JsonTestUtils.ts
Extract `ExpectedBounds` from `ExpectedShape` to prepare code sharing with the upcoming `Label Bounds` parsing
Introduce minor refactoring:
- rename label verification method to prepare the `Label Bounds` parsing
- remove unused code about Events verification
=> [REFACTOR] expected shape and bounds interface in tests

package-lock.json, package.json
Use fixed tagged version of ts-mxgraph instead of the last master commit
=> [INFRA] use a tagged version of ts-mxgraph

docs/bpmn-support.adoc, src/component/mxgraph/MxGraphConfigurator.ts, src/component/mxgraph/MxGraphRenderer.ts, src/component/mxgraph/ShapeConfigurator.ts, src/component/mxgraph/StyleUtils.ts, src/component/mxgraph/shape/event-shapes.ts, src/component/parser/json/converter/ProcessConverter.ts, src/model/bpmn/shape/ShapeBpmnElement.ts, src/model/bpmn/shape/ShapeBpmnElementKind.ts, src/model/bpmn/shape/ShapeUtil.ts, test/e2e/mxGraph.model.test.ts, test/unit/component/mxgraph/MxGraphRenderer.test.ts, test/unit/component/parser/json/BpmnJsonParser.event.boundary.interrupting.message.test.ts, test/unit/component/parser/json/JsonTestUtils.ts
Closes #309 
The parent mxCell of the mxCell of the boundary event is the pool/lane.
Example with B.2.0.bpmn, the timer boundary event in the middle of the screnshot belongs to a subprocess, currently not supported. As the boundary event is attached to the parent graph, it is displayed.
The parent mxCell of the mxCell of the boundary event is the activity.
As I use the same mechanism of event to calculte the kind of boundary events, we see all supported event kind (timer, message) as boundary.
I'll create in 2 next PRs the tests for the non-interrupting message & for interrupting timer.
The render is temporary. 
The color & the lines of the shape border will change later.
=> [FEAT] Display Interrupting Message Intermediate Event Attached to an Activity Boundary

docs/architecture/mxgraph-integration.adoc
=> [DOC] architecture doc about label bounds with mxgraph

docs/bpmn-support.adoc, src/component/mxgraph/shape/event-shapes.ts, test/e2e/mxGraph.model.test.ts
=> [FEAT] Render Interrupting Timer Intermediate Event Attached to an Activity Boundary

test/e2e/mxGraph.model.test.ts
This ensures that the BPMN element name are correctly set in the mxGraph model
prior being rendered.
Notice that this PR contains a refactoring required to simplify the label check introduction. It can be merged separately or squashed.
=> [TEST] check label values in mxgraph model e2e tests

docs/bpmn-support.adoc, src/component/mxgraph/StyleUtils.ts, src/component/mxgraph/shape/event-shapes.ts, test/e2e/mxGraph.model.test.ts
=> [FEAT] Render Non-interrupting Message Intermediate Event Attached to an Activity Boundary 

docs/bpmn-support.adoc, src/component/mxgraph/shape/event-shapes.ts, test/e2e/mxGraph.model.test.ts
=> [FEAT] Render Non-interrupting Timer Intermediate Event Attached to an Activity Boundary

CONTRIBUTING.md, README.md, docs/bpmn-support.adoc, docs/build-doc.bash, docs/index.adoc, docs/intro.adoc, package-lock.json, package.json, src/index.html, test/e2e/mxGraph.view.test.ts
We are developing a TypeScript library no we should not mention JavaScript or JS
in its name.
In addition, use the current repository url for the GitHub release badge.
=> [DOC] remove reference to 'JS' in library name

docs/bpmn-support.adoc, src/component/mxgraph/config/StyleConfigurator.ts, src/component/parser/json/converter/DiagramConverter.ts, src/component/parser/json/converter/ProcessConverter.ts, src/model/bpmn/shape/ShapeBpmnElementKind.ts, test/e2e/mxGraph.model.test.ts, test/unit/component/parser/json/BpmnJsonParser.label.bounds.test.ts, test/unit/component/parser/json/BpmnJsonParser.label.font.test.ts, test/unit/component/parser/json/BpmnJsonParser.label.test.ts, test/unit/component/parser/json/BpmnJsonParser.text.annotation.test.ts
**Display Text Annotation**
closes #94
=> [FEAT] Display Text Annotation

src/component/mxgraph/shape/IconPainter.ts, src/component/mxgraph/shape/render/BpmnCanvas.ts, src/component/mxgraph/shape/render/render-types.ts
Manage
- icon origin from top left shape: this avoids performing a 'hard' translate.
Such translate has side effects for subsequent painting: the origin has moved
so it would require to know that a back translate is needed. This will help
when managing activity markers.
- icon style: this currently introduces duplication with `IconPainter` that
will be removed when IconPainter will always use icon style
Covers #247
=> [REFACTOR] BpmnCanvas manages icon style and some 'icon origin'

docs/bpmn-support.adoc, src/component/mxgraph/config/StyleConfigurator.ts
Closes #389
The position of the edge will be fixed with #351 and/or #349
=> [FEAT] Render Message Flow with no message

docs/bpmn-support.adoc, src/component/mxgraph/config/ShapeConfigurator.ts, src/component/mxgraph/config/StyleConfigurator.ts, src/component/mxgraph/shape/text-annotation-shapes.ts, test/unit/component/mxgraph/config/StyleConfigurator.test.ts
=> [FEAT] Render Text Annotation

src/component/mxgraph/StyleUtils.ts, src/component/mxgraph/shape/IconPainter.ts, src/component/mxgraph/shape/render/BpmnCanvas.ts, src/component/mxgraph/shape/render/render-types.ts
Move all methods that set icon origin to `BpmnCanvas`
Remove `MxCanvasUtil` static utility
`IconPainter` additional refactoring: method signatures and rename
Covers #247
=> [REFACTOR] use `BpmnCanvas` in `IconPainter`

package-lock.json, package.json, src/component/mxgraph/StyleUtils.ts, src/component/mxgraph/config/MarkerConfigurator.ts, src/component/mxgraph/config/ShapeConfigurator.ts, src/component/mxgraph/shape/IconPainter.ts, src/component/mxgraph/shape/activity-shapes.ts, src/component/mxgraph/shape/event-shapes.ts, src/component/mxgraph/shape/gateway-shapes.ts, src/component/mxgraph/shape/render/BpmnCanvas.ts, src/component/mxgraph/shape/text-annotation-shapes.ts
More `mxgraph-type-definitions` usages in production code
- replace ts-mxgraph canvas2D types by mxAbstractCanvas2D when possible
- keep integer values for DEFAULT_DASHED and DEFAULT_FIX_DASH: the mxUtils
code isn't able to correctly convert the string into boolean
- update some TODO for remaining ts-mxgraph usages
covers #368
=> [INFRA] Bump mxgraph-type-definitions from 1.0.2 to 1.0.3

src/component/mxgraph/config/ShapeConfigurator.ts
This was due to wrong definitions of the canvas format method in
mxgraph-type-definitions@1.0.2. As we now use 1.0.3 which fixes this problem, we
can restore the code.
=> [REFACTOR] restore temporary commented mxShape createCanvas code

src/component/mxgraph/shape/activity-shapes.ts, src/component/mxgraph/shape/event-shapes.ts, src/component/mxgraph/shape/gateway-shapes.ts, src/component/mxgraph/shape/render/IconPainter.ts
Remove static calls to IconPainter which prevented to use alternate
implementation (by injection and for extension).
Introduce `IconPainterProvider` that returned an instance of `IconPainter` that
can be injected by configuration code. The new `IconPainterProvider` is now used
in all BPMN shapes when an `IconPainter` is needed.
Covers #247
=> [REFACTOR] add a way to inject and extend IconPainter

docs/bpmn-support.adoc, test/e2e/mxGraph.model.test.ts, test/fixtures/bpmn/model-complete-semantic.bpmn
=> [FEAT] Detect Interrupting Signal Intermediate Event Attached to an Activity Boundary

CONTRIBUTING.md
Clarify steps to avoid mistakes
=> [DOC] improve the release how-to

src/component/parser/json/converter/AbstractConverter.ts, src/component/parser/json/converter/CollaborationConverter.ts, src/component/parser/json/converter/DiagramConverter.ts, src/component/parser/json/converter/ProcessConverter.ts, src/component/parser/xml/bpmn-json-model/BPMN20.ts, src/component/parser/xml/bpmn-json-model/BPMNDI.ts, src/component/parser/xml/bpmn-json-model/baseElement/flowNode/event.ts, test/unit/component/parser/json/BpmnJsonParser.association.test.ts, test/unit/component/parser/json/JsonTestUtils.ts
Need in the future to simplify/merge BPMN Json model with our internal model, in order to remove some useless conversion
=> [BUG] Fix some types of BPMN Json model

CONTRIBUTING.md
Add missing manual steps for the `bpmn-visualization-examples` repository
=> [DOC] add new release steps

src/component/parser/json/converter/ProcessConverter.ts, src/component/parser/xml/bpmn-json-model/BPMN20.ts, test/unit/component/parser/json/BpmnJsonParser.event.test.ts, test/unit/component/parser/json/JsonBuilder.test.ts, test/unit/component/parser/json/JsonBuilder.ts, test/unit/component/parser/json/JsonTestUtils.ts
Closes #441 
- Refactor the event tests
- Fix the test for the boundary event attached to anything than an activity
=> [FIX] A boundary event can only be attached to an activity

docs/bpmn-support.adoc, src/component/mxgraph/shape/activity-shapes.ts, src/component/mxgraph/shape/render/IconPainter.ts, src/component/parser/json/converter/ProcessConverter.ts, src/model/bpmn/shape/ShapeBpmnMarkerKind.ts, test/e2e/mxGraph.model.test.ts, test/fixtures/bpmn/model-complete-semantic.bpmn, test/unit/component/mxgraph/config/StyleConfigurator.test.ts, test/unit/component/parser/json/BpmnJsonParser.marker.test.ts
=> [FEAT] Detect the Sequential Multi-instance Marker of an Activity

docs/bpmn-support.adoc, src/component/mxgraph/shape/activity-shapes.ts, src/component/mxgraph/shape/render/IconPainter.ts, src/component/parser/json/converter/ProcessConverter.ts, src/model/bpmn/shape/ShapeBpmnMarkerKind.ts, test/e2e/mxGraph.model.test.ts, test/fixtures/bpmn/model-complete-semantic.bpmn, test/unit/component/mxgraph/config/StyleConfigurator.test.ts, test/unit/component/parser/json/BpmnJsonParser.marker.test.ts
=> [FEAT] Detect the Parallel Multi-instance Marker of an activity

.github/dependabot.yml
It was previously using a 'update_configs' array (this is the configuration for
the dependabot version 1) instead of 'updates'.
=> [INFRA] fix dependabot configuration

src/component/mxgraph/shape/activity-shapes.ts
=> [FEAT] Render a Expanded/Collapsed Call Activity calling a Process

src/component/mxgraph/shape/activity-shapes.ts, src/component/mxgraph/shape/event-shapes.ts, src/component/mxgraph/shape/gateway-shapes.ts, src/component/mxgraph/shape/render/BpmnCanvas.ts, src/component/mxgraph/shape/render/IconPainter.ts, src/component/mxgraph/shape/render/render-types.ts
=> [REFACTOR] Call position methods in PaintParameter

docs/bpmn-support.adoc, src/component/mxgraph/shape/event-shapes.ts, src/model/bpmn/shape/ShapeBpmnEventKind.ts, test/e2e/mxGraph.model.test.ts, test/fixtures/bpmn/model-complete-semantic.bpmn, test/unit/component/parser/json/BpmnJsonParser.event.test.ts
=> [FEAT] Detect Error End Event & Error Interrupting Boundary Event

docs/bpmn-support.adoc, src/component/mxgraph/shape/event-shapes.ts, src/component/mxgraph/shape/render/IconPainter.ts
=> [FEAT] Render Error End Event & Error Interrupting Boundary Event

docs/bpmn-support.adoc, src/component/mxgraph/StyleUtils.ts, src/component/mxgraph/config/StyleConfigurator.ts, src/component/mxgraph/shape/activity-shapes.ts, test/e2e/mxGraph.model.test.ts, test/fixtures/bpmn/model-complete-semantic.bpmn, test/unit/component/mxgraph/config/StyleConfigurator.test.ts
=> [FEAT] Render Non-instantiating Receive task

src/component/parser/json/converter/ProcessConverter.ts, src/model/bpmn/shape/ShapeUtil.ts, test/unit/component/parser/json/BpmnJsonParser.sub.process.test.ts, test/unit/component/parser/xml/BpmnXmlParser.trisotech-bpmn-modeler-6_2_0.test.ts
closes #357 
closes #358
Events are now also detected in Event Sub-Process. They are currently rendered as Process Event (without dashed circle), this will be implemented later.
=> [FEAT] detect activities and gateways in subprocess

src/component/parser/json/converter/ProcessConverter.ts, test/unit/component/parser/json/BpmnJsonParser.sub.process.test.ts, test/unit/component/parser/xml/BpmnXmlParser.trisotech-bpmn-modeler-6_2_0.test.ts
**WIP depends on #514** 
closes #360 
This is final step to support regular inner elements. It contains a refactoring to ensure that process and sub-process elements are managed in the same way.
As a consequence, extra features for sub-process are availalble: inner subprocess, lane
In the following, the blank part inside the `event sub-process` are related to a not render `transaction sub-process` (not supported for now)
=> [FEAT] detect sequence flows of subprocess

test/e2e/mxGraph.model.test.ts, test/fixtures/bpmn/model-complete-semantic.bpmn, test/unit/component/parser/json/BpmnJsonParser.sub.process.test.ts
**WIP depends on ##517**
closes #384
No implementation, only tests to validate the parsing works.
With the file taken from https://github.com/process-analytics/bpmn-visualization-examples/pull/43
=>  [FEAT] Detect Error Start Interrupting Event on Event Sub-Processes

src/component/mxgraph/shape/activity-shapes.ts, src/component/mxgraph/shape/event-shapes.ts, src/component/mxgraph/shape/gateway-shapes.ts, src/component/mxgraph/shape/render/BpmnCanvas.ts, src/component/mxgraph/shape/render/IconPainter.ts
Add TSDoc in IconPainter and BpmnCanvas
Rename methods
- IconPainter `user task icon`: use a generic name (not related to woman even
if this is what we are painting by default) to clarify the method purpose
- BpmnCanvas `set icon origin`: clarify what methods do
This integrates feedbacks collected when implementing the first set of examples.
=> [REFACTOR] painting code easier to extend

src/component/mxgraph/config/StyleConfigurator.ts, src/component/parser/json/converter/DiagramConverter.ts, src/model/bpmn/shape/Shape.ts, test/unit/component/mxgraph/config/StyleConfigurator.test.ts, test/unit/component/parser/json/BpmnJsonParser.process.test.ts, test/unit/component/parser/json/JsonTestUtils.ts
=> [FEAT] Render Pool when Participant references a Process

test/e2e/mxGraph.model.test.ts, test/fixtures/bpmn/model-complete-semantic.bpmn
It now looks like (bpmn-js screenshot):
=> [TEST] Organize elements in model_complete_semantic.bpmn

CONTRIBUTING.md, jest-puppeteer.config.js
This is an attempt to avoid startup error when running GitHub Workflows on
macOS. This error probably occurs because the machines running the workflows
have low performances.
In addition, allow to configure puppeteer 'slowMo' with an environment variable
when debugging tests.
=> [TEST] increase puppeteer server launch timeout

src/component/mxgraph/shape/activity-shapes.ts
Closes #511 
Introduced a temporary way to generate task icon with a fixed size. This will be reworked and reviewed as part of #211 and #465 
Using diagram from https://github.com/process-analytics/bpmn-visualization-examples/pull/47
Using a diagram adapted from the non-regression tasks diagram from #523
=> [FEAT] Render Instantiating Receive Task

.github/workflows/release.yml, CONTRIBUTING.md
**Automatize release process - step 1**
The manually launched GH Workflow that automatizes:
- npm version bump
- tag creation
- tag push
- it overcomes the problem of pushing the tag to master
closes #139
=> [INFRA] Automate release process - step 1

docs/development/ide-configuration.md
Remove Jest plugin tips for VSCode, because it doesn't support multi configuration
=> [DOC] Remove Jest plugin tips for VSCode

README.md, docs/bpmn-support.adoc, docs/intro.adoc
Highlight environments in both README and html docs.
In addition
- update reference to current development milestones in html docs
- add license badge and update the `powered by statically.io` in the README
Please read the CONTRIBUTING guide prior creating a Pull Request.
Failure to do so may result in the rejection of the Pull Request.
=> [DOC] highlight demo and examples live environments

README.md, docs/architecture/development.adoc, docs/bpmn-support.adoc, docs/development/bpmn-support-how-to.md, docs/index.adoc, docs/intro.adoc, scripts/docs.js
Asciidoctor/html docs
- review supported browser list
- include favicon in html docs 
- add missing documentation about already supported start events for Event Sub-Process
Contributors
- better asciidoctor file display on GitHub
- BPMN support how-to: document how to credit the icons taken from external
sources
covers #433
=> [DOC] add various documentation improvements

test/e2e/mxGraph.model.test.ts
Add custom message when a cell is not defined
Closes #672
=> [TEST] Update error message in e2e tests

.gitignore, package.json, rollup.config.js, test-bundle/lib-integration-iife.html
The IIFE bundle can be manually tested by opening the local `/test-bundle/lib-integration-iife.html` file in a web browser
closes #601 
based on POC #645
=> [INFRA] Provide an IIFE bundle

.github/workflows/build.yml, scripts/utils/parseBpmn.ts
The issue has been introduced when moving the BpmnModel to a new folder.
We miss to update the script at that time.
To avoid this in the future, the GitHub build workflow now builds the utils
script at the end of the job to ensure we don't break anything.
=> [INFRA] fix the `parseBpmn` utils build

.npmignore, package.json
=> [INFRA] Prepare publish to npmjs

test/e2e/ExpectModelUtils.ts
=> [TEST] Convert expectFont function to jest extension

test/e2e/ExpectModelUtils.ts, test/e2e/matchers/index.ts, test/e2e/matchers/toBeEdge/index.ts, test/e2e/mxGraph.model.test.ts
- Convert 'expectModelContainsAssociationFlow' in Jest extension 'toBeAssociationFlow' 
- Remove useless 'toBeEdge' Jest extension
=> [TEST] Convert expectModelContainsAssociationFlow function to jest extension 

test/e2e/ExpectModelUtils.ts, test/e2e/matchers/index.ts, test/e2e/matchers/toBeShape/index.ts, test/e2e/mxGraph.model.test.ts
=> [TEST] Convert expectModelContainsLane to jest extension

package-lock.json, package.json, test/e2e/config/jest.image.ts, test/e2e/helpers/visu-utils.ts
Latest 4.1.2 version provides missing types related to jest-image-snapshot@4.2.0.
So no need for our custom types anymore.
=> [INFRA] use @types/jest-image-snapshot instead of custom types

package.json
`jest-each` is include in Jest: https://jestjs.io/docs/en/api
To avoid conflict of versions, no need to specify it as dependency.
=> [TEST] Remove unnecessary duplicated dependency: jest-each

src/demo/index.ts, src/index.html, src/static/js/demo.js, test/e2e/helpers/visu-utils.ts
- introduce functions to configure fit on load options from url parameters (all pages)
- introduce functions to configure demo elements (buttons and inputs)
- rename url parameter from `fitType` to `fitTypeOnLoad`
- debug: always log 'load options' after loading the diagram (previously, this was only done at configuration time)
Covers #738
=> [REFACTOR] Prepare the demo page for the fit after load

.github/release-drafter.yml
Previously, guidelines for release-notes remaining edits were provided as
comments, so they weren't visible in the displayed draft.
They are now visible in the rendered DRAFT to help not forgetting what has to
be done at release time.
=> [INFRA] more visible remaining manual edits in release-drafter template

.github/workflows/build.yml, README.md, package-lock.json, package.json, sonar-project.properties, test/e2e/jest.config.js, test/unit/jest.config.js
Add configuration to run a SonarCloud analysis on master branch and pull requests
Closes #823
=> [INFRA] Add SonarCloud analysis on CI build

.github/workflows/generate-documentation.yml
Only rebuild the documentation when the `users` content changes and not when the `contributors` content changes as it is not part of the sources used to build the HTML documentation.
=> [INFRA] Avoid extra html documentation rebuild

package.json
The pre-commit hook for linting is very useful because we always forget to run
it, especially when pushing.
Running 'tsc' seems also a good idea at the beginning of the project, but now,
it takes several seconds to complete which makes the commit experience boring.
This is particularly annoying for people that work with baby steps and commit
very frequently.
The gain of the of compilation check versus the time to wait before moving
forward don't worth the price: IDE or command line allows to run incremental
compilation fast and we almost never push code that don't compile.
=> [INFRA] Don't run 'tsc' in pre-commit hook

test/e2e/bpmn.navigation.test.ts, test/e2e/bpmn.rendering.test.ts, test/e2e/diagram.rendering.test.ts, test/e2e/helpers/visu-utils.ts
=> [TEST] Refactor the computing of the snapshot & diff paths for the visual tests

src/component/registry/bpmn-elements-registry.ts, src/demo/index.ts, src/elements-identification.html, src/static/js/elements-identification.js, test/e2e/helpers/visu-utils.ts, test/e2e/mxGraph.dom.test.ts, test/e2e/mxGraph.view.test.ts, test/fixtures/bpmn/registry/1-pool-3-lanes-message-start-end-intermediate-events.bpmn
Let pass one or several BPMN Kinds to get BpmnElements.
This implementation relies on CSS selectors for searching elements. It will be
possible to avoid this when the BpmnModel will be available and will provide
search capabilities (see #953).
closes #927
=> [FEAT] Add API to search elements by BPMN Kinds

src/component/mxgraph/MxGraphConfigurator.ts
As mxgraph enable it by default on right click, some extra configuration is
needed.
We also want to trigger panning over cells, but in that case, mxgraph ignores by
default the mouse button which has been clicked. So custom mxgraph code is
needed here.
In addition, improve the panning support on touch device: disable panning when
no navigation support.
closes #768
covers #847
=> [FEAT] Do not trigger panning on right click

src/component/BpmnVisualization.ts
Remove mxgraph browser support check
The implementation of `mxClient.isBrowserSupported())` always returns true as it
checks if the browser support svg or vml and all browser supported by the lib
support them.
No catch exception in the constructor
We previously already throw an Error, the alert was redundant. The calling code
must handle it anyway because no subsequent calls to bpmn-visualization function
will work
Don't use mxgraph code to create alert popup, which only calls `window.alert`
covers #54
=> [REFACTOR] Remove mxgraph code related to error management

.github/release-drafter.yml
Remove the extra spaces that prevented from applying bold to certain phrases in the template.
=> [INFRA] Fix release-drafter template

.github/workflows/build.yml, .github/workflows/upload-demo-archive.yml
The setup-node action already displays the node and npm version in the logs, so
there is no need to have a dedicated step calling the version options of these
tools.
=> [INFRA] Remove extra node installation check step in GitHub workflows

.github/workflows/generate-documentation-api.yml, .github/workflows/generate-documentation.yml
Let collaborators trigger generation with `workflow_dispatch`. This is useful
when the generated documentation is not in sync with the master branch.
=> [INFRA] Generate documentation on demand with GH workflows

.gitignore, src/component/mxgraph/MxGraphRenderer.ts, test/e2e/helpers/visu/ImageSnapshotConfigurator.ts
This simplifies test failures review, especially when checking GitHub workflows.
The html test report and the diff images are in the same directory.
The GitHub workflow also upload diff images in the test failures artifact without
extra configuration and there is no more need to dump the diff to the console. So we
also produce smaller and more manageable logs.
=> [TEST] Generate visual test diff images close to test reports

src/component/parser/json/converter/DiagramConverter.ts, test/unit/component/parser/json/BpmnJsonParser.edge.test.ts, test/unit/component/parser/json/BpmnJsonParser.label.bounds.test.ts, test/unit/component/parser/json/BpmnJsonParser.label.font.test.ts, test/unit/component/parser/json/BpmnJsonParser.label.test.ts
This is invalid and was not homogeneous with BPMN Shape that are not stored when
we don't get the bpmn element.
In addition, this can produced errors in client code as the bpmn element is not
supposed to be `undefined`.
A dedicated test has been added to manage this use case and parsing tests
that were relying on this 'hole' have been updated to use valid edge
BPMN sources (mainly tests about edge labels).
=> [FIX] Don't store 'edge without bpmn element' in the BpmnModel

src/component/parser/BpmnParser.ts, src/component/parser/json/converter/CollaborationConverter.ts, src/component/parser/json/converter/DiagramConverter.ts, src/component/parser/json/converter/EventDefinitionConverter.ts, src/component/parser/json/converter/GlobalTaskConverter.ts, src/component/parser/json/converter/ProcessConverter.ts
Catching errors and only log them hide parsing problems and generate new ones.
The parsing flow continues after an error is triggered which create side
effects: some valid data are missing and then are not available for the
subsequent parsing process. In that case, the model would be partially filled.
It is so better to propagate the error as it is not managed for now.
In addition, we don't have tests that show we can have such errors so we are not
even sure that such errors could occur.
=> [REFACTOR] Don't catch and only log warnings in the Json Parser

test/integration/dom.interactions.test.ts, test/integration/helpers/html-utils.ts
We load a file with all supported BPMN elements to ensure we don't have any
issue when producing the SVG.
The code coverage increases significantly as we now pass in all custom `mxGraph`
shapes when running the new tests. For instance, the integration tests coverage
for statements increases from `68.45%` to `93.04%`.
=> [TEST] Add more DOM integration tests

src/component/BpmnVisualization.ts
The `BpmnVisualization.bpmnModelRegistry` field was previously prefixed by a `_`
as this is sometime done in other projects as a convention to warn about private
fields in JS code. Remember that we don't produce private JS fields at TS
compilation as this not widely supported by browsers, so such fields are
ultimately visible.
This was not consistent with the rest of the code base, so the prefix has been
removed.
=> [REFACTOR] Don't use special prefix in private field name

.github/workflows/test-e2e.yml, README.md, test/e2e/bpmn.navigation.test.ts, test/e2e/bpmn.rendering.test.ts, test/e2e/diagram.rendering.test.ts, test/e2e/helpers/test-utils.ts, test/e2e/helpers/visu/image-snapshot-config.ts, test/e2e/overlays.rendering.test.ts
Skip panning tests on WebKit as they are not working for now.
They will be fixed later.
closes #876
=> [INFRA] Run WebKit e2e tests on macOS

src/component/mxgraph/BpmnMxGraph.ts
Revert additional specific macOS CMD support for simplification.
closes #773
=> [FEAT] Only trigger zoom with the CTRL on macOS

docs/contributors/testing.md, src/diagram-navigation.html, src/overlays.html
In addition, use `behavior` instead of `behaviour` everywhere for consistency.
Covers #926
=> [DOC] Use 'behavior' instead of 'interaction' when possible

.github/workflows/build.yml, .github/workflows/generate-demo-preview.yml, .github/workflows/generate-documentation.yml
This will prevent errors when Pull Request are created from forked repositories
and by Dependabot.
closes #1279
=> [INFRA] Skip GitHub workflow elements when secrets are not available

README.md, dev/ts/component/DropFileUserInterface.ts, dev/ts/demo.ts, dev/ts/helper.ts, dev/ts/internal-dev-bundle-index.ts, rollup.config.js, sonar-project.properties, src/bpmn-visualization.ts, test/e2e/jest.config.js, test/integration/jest.config.js, test/unit/jest.config.js
Move the demo and test-only code out of the main codebase. This clarifies that
is it is not part of the library and make it easier to not package it into the
bundles.
closes #717
=> [REFACTOR] Remove the demo code from the packaging

src/component/mxgraph/BpmnMxGraph.ts, test/e2e/helpers/visu/bpmn-page-utils.ts
The text is not selectable, so use the default cursor. This prevents to let
users think that the label is editable.
Fix #294
=> [FIX] Don't use a select text cursor on label hover

.eslintignore, src/component/mxgraph/config/ShapeConfigurator.ts, src/component/mxgraph/config/StyleConfigurator.ts, test/e2e/config/playwright.ts
Update the configuration to only ignore folders at project root. To prevent new
errors in the future, also do this for the `build` and `dist` folders.
Fix lint errors in files in the `config` folders.
=> [INFRA] Fix .eslintignore to consider files in `config` folders

docs/contributors/testing.md
Describe an alternate method and keep only general information to reduce
maintenance (avoid having out-of-date information, we previously miss the
'overlay' sub-folder).
=> [DOC] Contributors: improve how diagram are loaded in e2e tests

test/helpers/file-helper.ts
Use `bv:test` sub-namespace as in other tests for better log segmentation and
simpler activation.
=> [TEST] Update file-helper debug logger namespace

rollup.config.js
This has been introduced when moving the demo code to the `dev/ts` folder.
Prior the fix, when changing code in the src folder, the rollup typescript
plugin fails because it is unable to find the `dev/ts/internal-dev-bundle-index.ts`
source file.
[!] (plugin rpt2) Error: Could not find source file: 'xxxx/bpmn-visualization-js/dev/ts/internal-dev-bundle-index.ts'.
=> [INFRA] Fix typescript missing source when using livereload

src/component/mxgraph/StyleUtils.ts, src/component/mxgraph/config/StyleConfigurator.ts
Do not clone styles, inherit from the vertex and edge default style.
This allows to change a property at runtime in the default style and having the
change also applied to specific styles.
Previously, as all entries were cloned, integration had to apply the style
change to all styles.
=> [REFACTOR] Improve mxgraph style inheritance

dev/elements-identification.html
We now fill both the start and the end markers which changes the generated svg
structure.
We are subject to such changes until we implement #1035.
Prior the fix
With the fix
=> [TEST] Fix message flow css selector in test page

dev/diagram-navigation.html, dev/overlays.html
Ensure that '<!doctype html>' is on top of the page to conform to the HTML
specification.
This also prevent build tool like 'snowpack' to consider the page as an 'HTML fragment'
(which generates build errors).
Detected during the snowpack poc #1355. Snowpack error:
> [snowpack] Error: HTML fragment found!
> HTML fragments (files not starting with "<!doctype html>") are not transformed like full HTML pages.
> Add the missing doctype, or set buildOptions.htmlFragments=true if HTML fragments are expected.
>
=> [TEST] Update position of `doctype` in test pages

dev/ts/component/SvgExporter.ts, src/component/mxgraph/BpmnMxGraph.ts, src/component/mxgraph/overlay/custom-overlay.ts, src/component/mxgraph/shape/activity-shapes.ts, src/component/mxgraph/shape/edges.ts, src/component/mxgraph/shape/event-shapes.ts, src/component/mxgraph/shape/flow-shapes.ts, src/component/mxgraph/shape/gateway-shapes.ts, src/component/mxgraph/shape/text-annotation-shapes.ts, test/bundles/bundles.test.ts, test/e2e/helpers/visu/bpmn-page-utils.ts, tsconfig.json
Use the new TypeScript 4.3 override keyword: `TypeScript will always make sure
that a method with the same name exists in a the base class`.
Make override declaration mandatory: detect method removal in base class,
prevent to accidentally “trample over” a method that exists in a base class.
Also remove some public keywords on methods and constructors for simplicity
(this is the default) and consistency (we mostly avoid public keyword in this
case).
`Override` documentation: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-3.html#override-and-the---noimplicitoverride-flag
This may force integration to use TypeScript 4.3+ if the override keyword is present in the TS definitions. For now, the definitions generated from files touched by this PR are empty (strip …
=> [REFACTOR] Make override methods explicit

.github/release-drafter.yml
We mainly change dev dependencies that are only for the developers of the lib.
This list is often large and hid the maintenance efforts that was pushed back
at the very end.
=> [INFRA] List dependencies change at the end of the release notes

test/performance/bpmn.load.performance.test.ts, test/performance/bpmn.navigation.performance.test.ts
Introduced by a refactoring involving the PageTester class which is now located
in bpmn-page-utils.
=> [TEST] Fix imports in performance tests

test/e2e/diagram.navigation.zoom.pan.test.ts, test/e2e/helpers/test-utils.ts, test/e2e/helpers/visu/playwright-utils.ts, test/e2e/overlays.rendering.test.ts, test/performance/bpmn.navigation.performance.test.ts
They are now aligned with the 'mouse panning' functions and have more general
names (no more reference to mouse wheel or chromium which are implementation
details).
To prevent misuse, the 'zoom' function now fails when running on non chromium
browser (we currently can not manage mouse wheel with playwright).
=> [TEST] Rename 'mouse zoom' helper functions

src/component/parser/json/converter/CategoryConverter.ts, src/component/parser/json/converter/CollaborationConverter.ts, src/component/parser/json/converter/DiagramConverter.ts, src/component/parser/json/converter/EventDefinitionConverter.ts, src/component/parser/json/converter/GlobalTaskConverter.ts, src/component/parser/json/converter/ProcessConverter.ts
DiagramConverter: remove duplication
`convertedElements` property is now private instead of readonly because there
is no need to access it outside the class implementation
Declare static method when possible
=> [REFACTOR] Simplify Json Parsing Converters

.github/workflows/build.yml, .github/workflows/test-e2e.yml
https://github.blog/changelog/2021-08-16-github-actions-macos-11-big-sur-is-generally-available-on-github-hosted-runners/
=> [INFRA] Replace macOS 10.15 by macOS 11 (Big Sur) in the GitHub Actions

test/integration/dom.after.actions.test.ts
We have detected a bug in the R package but existing and new tests in the lib
don't exhibit the issue. The issue is in the JS code of the R package.
covers https://github.com/process-analytics/bpmn-visualization-R/issues/44
=> [TEST] Add more integration tests for 'requesting unknown bpmn element id'

src/component/BpmnVisualization.ts, src/component/mxgraph/BpmnMxGraph.ts, src/component/mxgraph/StyleUtils.ts, src/component/mxgraph/config/ShapeConfigurator.ts, src/component/mxgraph/shape/activity-shapes.ts, src/component/mxgraph/shape/event-shapes.ts, src/component/mxgraph/shape/render/BpmnCanvas.ts, src/component/options.ts, src/component/parser/json/converter/ProcessConverter.ts, src/component/registry/bpmn-elements-registry.ts, src/model/bpmn/internal/shape/ShapeBpmnElementKind.ts, src/model/bpmn/internal/shape/ShapeBpmnEventKind.ts, src/model/bpmn/internal/shape/ShapeBpmnSubProcessKind.ts, src/model/bpmn/internal/shape/ShapeUtil.ts, src/model/bpmn/internal/shape/index.ts, test/integration/dom.after.actions.test.ts, test/unit/component/mxgraph/renderer/StyleComputer.test.ts, test/unit/component/mxgraph/shape/render/BpmnCanvas.test.ts, test/unit/component/parser/json/BpmnJsonParser.event.test.ts, test/unit/component/parser/json/BpmnJsonParser.marker.test.ts, test/unit/component/parser/json/BpmnJsonParser.sequenceFlow.conditional.test.ts, test/unit/component/parser/json/BpmnJsonParser.sequenceFlow.default.test.ts
We have too much TODO in the code, some are redundant or already described in
GitHub issues. So, perform some cleaning and do some quick fixes.
Support for new elements and related tests
- The documentation already explains how to do it, so no need to have a TODO
for that in the code.
- The comments have been kept and simplified in ShapeBpmnEventKind as a
guideline (no more split across all files) and parsing tests. There is a
particular highlight for Subprocess.
- parsing tests: reorder kind declaration in the 'each' statement (keep kind
family together)
Information already in issues or documentation
- BpmnVisualization.ts load: error handling
- BpmnMxGraph.ts customFit: extra fit
- ShapeConfigurator.ts: mxgraph custom code will be reviewed on mxgraph bump
- activity-shapes and …
=> [REFACTOR] Manage and clean some TODOs

.editorconfig, src/component/mxgraph/StyleUtils.ts, src/component/mxgraph/config/StyleConfigurator.ts
StyleDefault SHAPE_ACTIVITY_MARKER_ICON_SIZE
Implicitly managed with the issue to have a true marker fixed size.
StyleConfigurator: lane and pool label style. Documented in the issue.
editorconfig: we use os eol and let git manage eol on push
This setting may only be needed for windows, but default git checkout config
handle it correctly.
So remove the todo about setting a specific configuration.
=> [REFACTOR] Manage some todo

src/component/mxgraph/StyleUtils.ts
They are related to 'dash' styles. They are not used directly in the code nor
in examples.
**This is not a breaking changes**
Nobody is supposed to use the former code, so there is no need for notifying end-user about that.
=> [REFACTOR] Remove unused functions and constants in StyleUtils

src/component/mxgraph/StyleUtils.ts, src/component/mxgraph/config/ShapeConfigurator.ts, src/component/mxgraph/config/StyleConfigurator.ts, src/component/mxgraph/shape/activity-shapes.ts, src/component/mxgraph/shape/event-shapes.ts, src/component/mxgraph/shape/gateway-shapes.ts, src/component/mxgraph/shape/text-annotation-shapes.ts, test/integration/matchers/toBeShape/index.ts
We don't configure styles in mxgraph BPMN shapes anymore. All styles are now
fully configured with StyleConfigurator and StyleDefault,
so the whole styling options can be changed more easily.
The shape classes have then been simplified: some have been removed and most
constructors have been removed.
=> [REFACTOR] Always configure styles out of mxgraph BPMN shapes

test/integration/dom.after.actions.test.ts
We only had integration tests that used the HTMLElement id. Improve coverage by
also passing the HTMLElement instance.
=> [TEST] Add tests for lib initialization using HTMLElement container

src/bpmn-visualization.ts
It was only needed by custom theme examples using the IIFE bundle to get
mxgraph constants.
The examples have been updated and now use a new way to customize the theme.
This PR rollbacks #1092 that had been introduced in [bpmn-visualization@0.12.1](
https://github.com/process-analytics/bpmn-visualization-js/releases/tag/v0.12.1)
=> [REFACTOR] Don't export mxgraph mxConstants

src/component/mxgraph/shape/activity-shapes.ts, src/component/mxgraph/shape/render/utils.ts
Remove the extra code for the "3 markers case".
We never have 3 markers for now, so the defensive code throwing an error is
never reached.
It will be correctly implemented when managing the initial rendering or the adhoc
subprocess or the compensation marker.
Also simplify the implementation of the 'orderActivityMarkers' function.
Covers #308, #356, #347, #355
This won't happen until we start working on new markers. During this implementation, instead of an error at rendering time, we will see overlapping markers. This is a good signal for developers that it is time to manage more than 2 markers in the mxgraph rendering code.
For a preview of the markers overlapping, here is what we see when we artificially add an extra marker in the code that fills the mxGraph model. The following …
=> [REFACTOR] Simplify markers computation during rendering

README.md
Hacktoberfest 2021 is now over, so there is no need to advertise the event anymore.
=> [DOC] Restore the regular hero image in README

package.json
Use the recommend way to run `husky install`.
Following : https://blog.typicode.com/husky-git-hooks-autoinstall/
Update script (remove the `postInstall` script that previously existed):
```
// package.json
{
"scripts": {
"prepare": "husky install"
}
}
```
And run it locally (also run as part on npm install):
`npm run prepare`
=> [INFRA] Update Husky installation

src/component/parser/json/converter/DiagramConverter.ts, src/component/parser/json/converter/ProcessConverter.ts
We have decided that we will keep the internal and json model separated.
So we won't merge/simplify `AssociationDirectionKind` and `MessageVisibleKind`
that will stay present in the 2 models.
=> [REFACTOR] Remove TODO about model enum conversion

test/e2e/bpmn.rendering.test.ts
Locally tested on Ubuntu 20.04.3 LTS.
=> [TEST] Update visual test thresholds for local run on Chromium Ubuntu

src/component/mxgraph/BpmnRenderer.ts
Always returns a parent, there is no need for a dedicated code for boundary
events. They are supposed to be attached to an existing parent.
More generally, if the parent id is set, it is set correctly by the parsing code.
Otherwise, it means that the parsing code contains bugs.
We don't have tests that demonstrate the need for such special use case. So
remove this defensive code and use a convenient default.
The defensive code has been introduced on 2020-06-23 with #323, prior having visual tests.
It was then updated on 2020-10-23 with #821. It may have been needed in the past, but tests show that we don't need it.
Notice that we already simplified the code on 2021-08-19 with #1486.
Removing the code removes a `TODO`, decreases the lib size, and increases the code coverage.
See also the …
=> [REFACTOR] Simplify parent retrieval in BpmnRenderer

test/integration/dom.after.actions.test.ts, test/integration/helpers/html-utils.ts
Introduce a common `RequestedChecks` for methods of `HtmlElementLookup`. This
improves readability and maintenance: there is no need to add new parameters
when new checks are implemented in methods.
Prepares tests for #1621 and #1622
=> [TEST] Define the same signature for svg expect functions

dev/public/diagram-navigation.html, dev/public/elements-identification.html, dev/public/index.html, dev/public/lib-integration.html, dev/public/non-regression.html, dev/public/overlays.html
Previously, we put the script declaration at the end of the page body, it
allowed the elimination of parser-blocking JavaScript.
The `defer` attribute is designed for such a purpose.
We only load a single module script in each page, and modules are deferred
automatically. So, we can declare the scripts in the head of the page without
using the defer attribute.
Resources:
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules#other_differences_between_modules_and_standard_scripts
- https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script#attr-defer
=> [EXAMPLE] Use deferred script loading

test/integration/dom.after.actions.test.ts, test/integration/helpers/html-utils.ts, test/integration/helpers/semantic-with-svg-utils.ts
- Move utils code out of integration test files
- Reuse HtmlLookup instances when possible in tests
- Move computeClassValue out of HtmlElementLookup: avoid static method call
for clarity
=> [TEST] Reorganize utils code in integration tests

dev/public/elements-identification.html
Style on hover is not applied passing on the text.
The style is inspired of what we did in https://github.com/process-analytics/bpmn-visualization-examples/pull/265.
Covers #920
Can be accessed locally using http://localhost:10001/elements-identification.html?url=./static/diagrams/labels.01.general.bpmn
=> [TEST] Reproduce 'BPMN text label ignored events' in example page

README.md
Fixes
- browser usage: there aren't tips below the example about how to get the BPMN content
- license dates: clarify from-to years
=> [DOC] Improve wording in README

src/component/mxgraph/config/ShapeConfigurator.ts
Closes #920
Can be accessed locally using http://localhost:10001/elements-identification.html?url=./static/diagrams/labels.01.general.bpmn
Before (#1641) | Now
-------- | --------
Initially, I thought that a mxGraph version bug would fix the problem. I have tested to cherry pick a fix from mxgraph 4.2.1 here, but it didn't work. After a deeper review, it if for SVG text node (this is what we use for overlays), not for foreignObject that we are using for label. See 3b5938b.
So, I reimplement `mxSvgCanvas.getTextCss` and to set the `event-pointers` style property to `none`.
=> [FIX] Fixes ignored pointerEvents for BPMN Label

docs/users/bpmn-support.adoc
Label fonts default were documented several times, the fill and stroke color
defaults weren't visible.
We now have a dedicated block for documenting defaults.
=> [DOC] Centralize the documentation of default styles

src/component/registry/bpmn-elements-registry.ts, src/component/registry/bpmn-model-registry.ts, src/component/registry/css-registry.ts, test/integration/dom.after.actions.test.ts, test/integration/helpers/html-utils.ts, test/unit/component/registry/bpmn-model-registry.test.ts, test/unit/component/registry/css-registry.test.ts
closes #1637
Previously, without the cache clean, classes added to a diagram were kept when
loading a new one. So, the DOM element produced after loading a new diagram
could receive an extra class added for the previous diagram.
The cache stored by CssRegistry can now be cleared, and it is cleared on new
diagram load to avoid such an issue.
In addition
- remove the hack introduced to not face the bug when testing message flow icon
- add a unit test to demonstrate we cannot accidentally modify the classes
cache without using the API
=> [FIX] Ensure extra CSS classes are cleaned on diagram load

dev/public/elements-identification.html, dev/public/static/js/elements-identification.js, src/component/mxgraph/MxGraphCellUpdater.ts, src/component/registry/query-selectors.ts, test/e2e/helpers/visu/bpmn-page-utils.ts, test/helpers/query-selectors.ts, test/integration/dom.after.actions.test.ts, test/integration/helpers/html-utils.ts
The extra css classes added via the API weren't applied to label except when
triggering a full diagram redraw i.e. on zoom or panning.
Most of the work done here involved reproducing the issue with integration tests.
They required to tweak the mxGraph configuration as mxGraph was not generating
foreign objects. This seems due to the jsdom environment. Forcing `NO_FO` to
`false` switch the label generation to what we have in the browser.
The integration tests now test the label text and css classes for lane, user
task, sequence flow, start and end events.
In MxCellUpdater, remove call to `state.shape.apply(state)`
This code applied the style of the given `mxCellState` to the shape and only
default styles known by mxGraph.
The 'extra css style' is not taken from the shape but from the …
=> [FIX] Always apply extra CSS classes to label nodes

src/component/BpmnVisualization.ts, src/component/registry/bpmn-model-registry.ts, test/unit/component/registry/bpmn-model-registry.test.ts
The new name better explains what the method does and is now consistent with the
callback property.
=> [REFACTOR] Rename the 'load' method in ModelRegistry

src/model/bpmn/internal/edge/kinds.ts, src/model/bpmn/internal/index.ts, test/integration/mxGraph.model.bpmn.elements.test.ts
They are required at least for full styling capacities
  - AssociationDirectionKind
  - MessageVisibleKind
  - SequenceFlowKind
They are now part of the API documentation generated by Typedoc.
=> [FIX] Export some missing flow kinds

src/model/bpmn/internal/shape/utils.ts, test/unit/model/bpmn/internal/shape/utils.test.ts
The internal arrays were leaked outside the lib, so an accidental modification of the returned array was persisted.
After such a modification, the parsing and the rendering may not work correctly, especially if some elements were removed.
`ShapeUtil` now always returns a copy of a reference array instead of the array itself.
=> [FIX] Prevent external modification of reference shape kinds

dev/public/elements-identification.html
Update `elements-identification.html` to better demonstrates that we have dedicated CSS classes to style the icon regardless of the style of the message flow.
http://localhost:10001/elements-identification.html?url=./static/diagrams/registry/message-flows-with-and-without-icon.bpmn
#1640 | now| 
-------- | -----------
As a reminder, hover on icon and flows are not the same
=> [EXAMPLE] Use specific stroke and fill colors for msg flow icons

.github/workflows/build.yml, .github/workflows/test-e2e.yml
Replace the Playwright GitHub Action by the Playwright CLI, like it's recommended by the [documentation of the Github Action](https://github.com/microsoft/playwright-github-action) and following the [documentation of the CLI](https://playwright.dev/docs/cli/#install-system-dependencies).
=> [INFRA] Replace the Playwright GitHub Action by the Playwright CLI

package-lock.json, package.json, test/bundles/bundles.test.ts, test/bundles/jest.config.js, test/e2e/diagram.navigation.zoom.pan.test.ts, test/e2e/helpers/test-utils.ts, test/e2e/helpers/visu/bpmn-page-utils.ts, test/e2e/jest.config.js, test/e2e/overlays.rendering.test.ts, test/integration/jest.config.js, test/performance/bpmn.navigation.performance.test.ts, test/performance/jest.config.js, test/unit/jest.config.js, tsconfig.test.json
In this PR, you can find:
- The installation & the configuration of the [expect-playwright](https://github.com/playwright-community/expect-playwright) dependency
- The renaming of `tsconfig.jest.json` file in `tsconfig.test.json` in order to respect the IntelliJ convention for multiple tsconfig files
- The usage of the `expect-playwright` assertions
- and some refactoring
To check if a test failed, I replace some assertions by a wrong CSS selector, and other with a wrong expected value.
=> [INFRA] Use expect-playwright in tests

test/e2e/bpmn.rendering.test.ts, test/e2e/diagram.navigation.fit.test.ts, test/e2e/diagram.navigation.zoom.pan.test.ts, test/e2e/helpers/visu/bpmn-page-utils.ts, test/e2e/overlays.rendering.test.ts, test/performance/bpmn.load.performance.test.ts, test/performance/bpmn.navigation.performance.test.ts
We don't like using globals and this change prepares an eventual move to `playwright-test` which doesn't provide a `Page` global.
This was already done in `PageTester` subclasses, so this is now more consistent.
=> [TEST] Avoid usage of the Playwright page global in PageTester

test/e2e/diagram.navigation.fit.test.ts, test/e2e/diagram.navigation.zoom.pan.test.ts, test/e2e/helpers/test-utils.ts, test/e2e/helpers/visu/bpmn-page-utils.ts, test/e2e/overlays.rendering.test.ts, test/performance/bpmn.navigation.performance.test.ts
We don't like using globals and this change prepares an eventual move to `playwright-test` which doesn't provide a `Page` global.
Also update the `BpmnPage.page` property for consistency with other classes.
=> [TEST] Avoid usage of the PW page global in utils functions

src/component/mxgraph/BpmnMxGraph.ts, src/component/mxgraph/shape/event-shapes.ts
EventShape: remove commented code. We currently have no plan about implementing the remaining event definitions. We will add the code again when/if we decide to add the missing definitions.
BpmnMxGraph: remove unnecessary cast and remove TODO.
typed-mxgraph method signature has been fixed, so we don't need the workaround we previously used.
=> [REFACTOR] Fix remaining SonarCloud issues

README.md
The README is bundled in the npm package. In that case, the other documentation
source files are not available. There are online services that use the README
as the home page of the library (npmjs, skypack and others). In that case, the
link to the BPMN Support documentation is broken.
The direct use of the documentation url fixes the issue.
See https://www.skypack.dev/view/bpmn-visualization for instance.
=> [DOC] Reference the BPMN Support doc instead of source in README

src/component/BpmnVisualization.ts, src/component/mxgraph/BpmnGraph.ts, src/component/mxgraph/BpmnRenderer.ts, src/component/mxgraph/GraphCellUpdater.ts, src/component/mxgraph/GraphConfigurator.ts, src/component/mxgraph/config/StyleConfigurator.ts, src/component/mxgraph/renderer/CoordinatesTranslator.ts, src/component/registry/bpmn-elements-registry.ts
Remove the 'mx' prefix for clarity. They are stored in mxgraph sub-folders and their name is clear enough to understand they are related to mxGraph.
=> [REFACTOR] Rename classes and functions related to mxGraph

.github/dependabot.yml
Automatic rebases triggered too much GH Actions run, in particular for PR that are on hold because they require manual tests or changes (on breaking changes).
They used a lot of runners so we had job in queue for PR that we wanted to merge in priority.
Now, we ask dependabot to rebase a PR just prior we want to merge it.
**Notes**
If validated, we should apply the same change to the website repository (and to other repo that make dependabot update the dependencies
=> [INFRA] Disable dependabot PR auto rebase

README.md, rollup.config.js, src/component/mxgraph/BpmnRenderer.ts, src/component/mxgraph/GraphCellUpdater.ts, src/component/mxgraph/style/utils.ts, src/component/parser/json/converter/utils.ts, src/component/parser/json/warnings.ts, src/component/registry/bpmn-elements-registry.ts, src/component/registry/bpmn-model-registry.ts, test/bundles/bundles.test.ts, tsconfig.bundle.json
In the npm package, the definitions were previously located in dist/src instead of in dist/. It also contained development/demo types in dist/dev. So, project integrating bpmn-visualization were unable to retrieve the types and got errors like TS7016: Could not find a declaration file for module 'bpmn-visualization'
The issue was located in the rollup configuration that override the tsconfig file when building the npm package. The 'include' configuration was not correctly overridden, so we used the development values.
This is now fixed and there is a new test that will prevent this from happening again.
Some definition files previously referenced types or classes that were not defined. Such elements are marked as internal and strip from the definitions.
So this was generating errors like …
=> [FIX] Fix the type definitions

README.md, package.json, scripts/manage-version-suffix.mjs, src/bpmn-visualization.ts, src/component/BpmnVisualization.ts, src/component/version.ts, test/integration/BpmnVisualization.test.ts
Introduce the `getVersion` method to retrieve bpmn-visualization and mxGraph
version used at runtime. This should help debugging project that use newer
mxGraph version that currently cause issue like v4.2.2.
The bpmn-visualization version is automatically updated at release time by the
in-place script that already update the version of the package.json and sonar
files.
The lint configuration has been updated to ensure the script is part of the lint
process (all mjs files).
About mxGraph@4.2.2, see https://github.com/process-analytics/bpmn-visualization-js/pull/1814#discussion_r806569775
I ran the following test
- version update: `node scripts/manage-version-suffix.mjs`
- types generation: `./node_modules/.bin/tsc --emitDeclarationOnly --declaration`
- API doc review
Other PR will be …
=> [FEAT] Add new API to get version information

dev/public/index.html, src/component/options.ts
The rendering remains unchanged for desktop.
Create the dedicated configuration for the responsive layout and fix the
viewport to ensure the responsiveness is actually triggered on mobile.
Additions
- zoom options in the demo page: no number range + display the actual default
values
- fix the documentation related to zoom options in options.ts
Follow implementation of #1828 
v0.21.5 | #1828 | now 
------ | ------ | ------
**With Firefox emulator**
Galaxy Note 20 | iPhone 12/13 Pro
------ | ------
**With real devices**
iPhone 8 Firefox (same with webkit). The select box height is larger so there is an alignment issue. I suggest we eventually rework the layout later but for sure, I won't update it in this PR
=> [EXAMPLE] Improve the layout of the demo for mobile

.github/release-drafter.yml, .github/workflows/fill-gh-draft-release.yml, docs/contributors/maintainers.md
`release-drafter` configuration
- use a specific action version to better control updates and the use of new features. dependabot will create PR for action updates when new release-drafter releases are available
- 'Dependencies' category: collapsed if more than 5 elements
- exclude dependabot from the CONTRIBUTORS list. We removed it manually on every release so make it automatically
- allow running release-drafter on demand. This is useful to fix the release notes after PR relabel
Release documentation
Update the documentation of the release procedure for the GitHub release update
It should help us to detect wrong updates by release-drafter and loosing work because it overrides our manual edits.
**Notes**
During the release of verison 0.22.0, release-drafter override manual edits we were …
=> [INFRA] Improve the release-notes generation and documentation

.github/release-drafter.yml
- remove dependabot from the contributors list
- don't replace dependabot user (no impact in the dependencies list but avoid side effects in the contributors list removal)
Tested in https://github.com/process-analytics/github-actions-playground/ (see https://github.com/process-analytics/github-actions-playground/pull/40 and https://github.com/process-analytics/github-actions-playground/pull/41 + the generated draft)
before | now
-------- | --------
=> [INFRA] Improve contributors list detection by release-drafter

README.md, package-lock.json, package.json
Some exported types like `BpmnCanvas` references mxgraph types
`/// <reference types="typed-mxgraph" />`
These forced project integrating bpmn-visualization to manually declare
typed-mxgraph as dependency to not get TypeScript type errors.
Declaring it as a production dependency makes it automatically available to
project and simplify their configuration.
This is the use case described in https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html#dependencies
I also test the change with the TS vite project in the examples repository.
https://github.com/microsoft/TypeScript-Website/blob/377bb75d61ca12717c043b3c539b8f81d4c111ac/packages/documentation/copy/en/declaration-files/Publishing.md#dependencies
```json
{
"name": "browserify-typescript-extension",
"author": …
```
=> [INFRA] Declare `typed-mxgraph` in production dependencies

package-lock.json, package.json
With this release, typed-mxgraph doesn't declare mxgraph as peerDependencies.
This should avoid side effects on project that need to directly use mxgraph, for instance for extension.
**Notes**
typed-mxgraph@1.0.5 release notes: https://github.com/typed-mxgraph/typed-mxgraph/releases/tag/v1.0.5
About the peerDependencies, see https://github.com/process-analytics/bpmn-visualization-examples/pull/297#issuecomment-1060522329
=> [INFRA] prod - Bump typed-mxgraph from 1.0.4 to 1.0.5

dev/public/elements-identification.html
The following elements weren't highlighted in the past implementation of `elements-identification.html`:
- conditional: arrow
- default: marker and arrow
With the `test/fixtures/bpmn/non-regression/flows.sequence.01.kinds.and.complex.paths.bpmn` diagram
before | now
------- | -------
=> [EXAMPLE] Better highlight conditional and default sequence flows

package.json, scripts/manage-version-in-files.mjs
Remove the call to the `cross-env `command from the custom npm `version` script as it is not available at runtime in the release GitHub workflow.
Dependencies are not available as we are not running `npm ci` prior running `npm version`.
We are now using the Linux syntax which is not an issue as we always run the npm script from the GitHub workflow (never run locally).
Refs #1858
Tested by running `npm run version-prepare && npm version patch --no-commit-hooks --message "[RELEASE] %s"` on  Ubuntu 20.04.4 LTS
=> [INFRA] Fix the release GitHub workflow

README.md
The former list was referencing old browsers for bpmn-visualization@0.13.0 released on 2021-03-22.
=> [DOC] Update the list of working browsers with v0.23.0

package-lock.json, package.json, rollup.config.js, utils.rollup.config.mjs
We don't import json resources in the code, so this plugin is useless. Removing it from the Rollup
configuration simplify the maintenance (smaller configuration file, less development dependencies).
=> [INFRA] Remove declaration of the rollup json plugin

.github/workflows/generate-demo-preview.yml, .github/workflows/generate-documentation.yml
When closing the Pull Request, the only thing to do is to run the surge teardown. So skip other actions in this case.
This is what is done in the [playground repository](https://github.com/process-analytics/github-actions-playground/blob/5d35937bbd5ac92a0bceda3ce313c7e698d895c3/.github/workflows/surge-preview-for-pr.yml#L28).
Also done in https://github.com/process-analytics/process-analytics.dev/pull/478
=> [INFRA] Simplify surge preview teardown

.github/workflows/test-e2e.yml
Some tests involving BPMN label are not passing anymore, without any code code nor dependencies changes.
Disable them to give us time to investigate without stopping developments.
covers #1933
=> [INFRA] Temporarly disable Chrome and Edge e2e tests on CI

.github/workflows/test-e2e.yml
We recently updated playwright to version 1.22.1. The Chromium version was bump, so we changed the screenshots and thresholds.
As this Chromium version is more up to date with the latest Chrome and Edge version, the test configuration changes correctly apply to these 2 browsers.
closes #1933 
tested with #1935
=> [INFRA] Restore Chrome and Edge e2e tests on CI

.github/workflows/upload-demo-archive-and-trigger-examples-repository-update.yml
The artifact name contained extra enclosing quotes. It made the manual PR creation in the examples repository harder to do and broke the contract between the 2 repositories.
closes #1972 
Tested in the playground repository, see https://github.com/process-analytics/github-actions-playground/pull/89#issuecomment-1128928494
=> [INFRA] Fix released demo artifact name

.gitignore, dev/public/diagram-navigation.html, dev/public/elements-identification.html, dev/public/index.html, dev/public/lib-integration.html, dev/public/non-regression.html, dev/public/overlays.html, dev/public/static/js/diagram-navigation.js, dev/public/static/js/elements-identification.js, dev/public/static/js/index.js, dev/public/static/js/lib-integration.js, dev/public/static/js/non-regression.js, dev/public/static/js/overlays.js, docs/contributors/demo-page-css.md, docs/contributors/development.md, docs/contributors/testing.md, index.html, package-lock.json, package.json, postcss.config.js, rollup.config.js, scripts/prepare-demo-for-publish.mjs, test/config/jest-playwright.js, test/e2e/helpers/visu/bpmn-page-utils.ts, test/e2e/jest.config.js, test/performance/jest.config.js, tsconfig.json, vite.config.js
We benefit from the ViteJS 'unbundled' way of working: the dev server starts and updates in 200-300 ms instead of 13-18
seconds.
We also have a much better integration for tailwindcss than with the custom hack we previously used.
Rollup configuration simplification
- Remove the former Rollup configuration used to build the demo and run the development server.
- Only keep the bundles build configuration.
- Remove some dev dependencies that are no longer needed
Improvements in e2e tests
- No need to copy the diagrams, the dev server exposes the diagrams source folders
- Use the same dev server instance in tests and development and reduce the launchTimeout locally as it starts very
fast
Demo: only keep 2 pages, others are for test only
based on #1416
closes #596
=> [INFRA] Use ViteJS for development and the demo build

dev/public/diagram-navigation.html, dev/public/elements-identification.html, dev/public/index.html, dev/public/lib-integration.html, dev/public/non-regression.html, dev/public/overlays.html, dev/public/static/js/diagram-navigation.js, dev/public/static/js/elements-identification.js, dev/public/static/js/index.js, dev/public/static/js/lib-integration.js, dev/public/static/js/overlays.js, dev/ts/component/DropFileUserInterface.ts, dev/ts/component/ThemedBpmnVisualization.ts, dev/ts/component/download.ts, dev/ts/dev-bundle-index.ts, dev/ts/main.ts, dev/ts/utils/internal-helpers.ts, dev/ts/utils/shared-helpers.ts
Simplify how TS code is imported in static JS file and how assets are loaded in page
The previous syntax work for the Vite dev server and demo bundling, but was not understood by IDE. We now use relative
paths that make code navigation possible.
Reorganize code to clarify what is internal and what is shared by example and test code
- rename TS entry point for demo and test pages
- move utils code in dedicated files
=> [DEMO] Simplify imports and asset loading in sources

.github/actions/build-setup/action.yml, .github/workflows/build.yml, .github/workflows/generate-demo-preview.yml, .github/workflows/generate-documentation.yml, .github/workflows/publish-npm.yml, .github/workflows/release.yml, .github/workflows/test-e2e.yml, .github/workflows/upload-demo-archive-and-trigger-examples-repository-update.yml, scripts/manage-version-in-files.mjs
Introduce a local `GitHub Action` to configure node and perform `npm ci` with the right configuration (disable
playwright browser download).
The npm dependencies cache and dependencies installation are now managed with the `bahmutov/npm-install` actions which has sensible good defaults
Pass options to npm ci to
- improve the cache usage (--prefer-offline)
- skip post-install scripts (--ignore-scripts). We don't need them to run on CI and this will block malicious script that try to steal  tokens (on npm publish for instance)
- ✔️  no more `npm audit`
- ✔️ still no browsers download on `npm ci`
<details>
<summary>build workflow run on ubuntu - npm-install GitHub Action</summary>
<pre>
Run bahmutov/npm-install@v1
running npm-install GitHub Action
trying to restore cached NPM modules …
=> [INFRA] Remove build setup duplication in GitHub workflows

src/component/BpmnVisualization.ts, src/component/mxgraph/BpmnRenderer.ts, test/integration/BpmnVisualization.test.ts, test/integration/diagram.navigation.test.ts, test/integration/helpers/fit-utils.ts
Add missing tests for 'load with fit' and reorganize the 'fit' tests.
Also simplify the signature of the `BpmnRenderer.render` method. There is no need to pass the whole `LoadOptions` as it only
use the `FitOptions`.
=> [TEST] Improve integration tests of the load API

test/unit/component/mxgraph/renderer/StyleComputer.test.ts, test/unit/component/parser/json/BpmnJsonParser.association.test.ts, test/unit/component/parser/json/BpmnJsonParser.callActivity.test.ts, test/unit/component/parser/json/BpmnJsonParser.diagram.test.ts, test/unit/component/parser/json/BpmnJsonParser.event.test.ts, test/unit/component/parser/json/BpmnJsonParser.flowNode.test.ts, test/unit/component/parser/json/BpmnJsonParser.group.test.ts, test/unit/component/parser/json/BpmnJsonParser.lane.test.ts, test/unit/component/parser/json/BpmnJsonParser.marker.test.ts, test/unit/component/parser/json/BpmnJsonParser.messageFlow.test.ts, test/unit/component/parser/json/BpmnJsonParser.process.test.ts, test/unit/component/parser/json/BpmnJsonParser.sequenceFlow.conditional.test.ts, test/unit/component/parser/json/BpmnJsonParser.sequenceFlow.default.test.ts, test/unit/component/parser/json/BpmnJsonParser.sequenceFlow.normal.test.ts, test/unit/component/parser/json/BpmnJsonParser.sub.process.test.ts, test/unit/component/parser/json/BpmnJsonParser.text.annotation.test.ts, test/unit/component/parser/json/JsonTestUtils.ts
`JsonTestUtils` re-exported all exports of `helpers/bpmn-model-expect`.
This was a temporary solution after the `verifyShape` and `verifyEdge` functions were moved to the `bpmn-model-expect` file.
The re-export is now removed.
=> [TEST] Simplify imports of expected model elements

.github/actions/custom-surge-preview/action.yml, .github/workflows/generate-demo-preview.yml, .github/workflows/generate-documentation.yml
Remove duplication by introducing a custom action. We now run a single job instead of 2 jobs with cryptic secret checks.
Delegate most of the work to the https://github.com/bonitasoft/actions `surge-preview-tools` action to better manage PR created from fork repositories or by Dependabot.
We shouldn't have error on PR close when it was created by dependabot: most of the time the preview doesn't exist. We previously had errors because we always tried to teardown the surge domain even when it didn't exist. This is now fixed.
Previously valided with https://github.com/process-analytics/github-actions-playground/pull/103
=> [INFRA] Improve surge preview workflows

src/component/BpmnVisualization.ts
Typedoc 0.23 changed the way it renders 'experimental' tags. Previously, we could have a message explaining why it was
experimental. Typedoc did display the message close to the tag. Now, it put the tag close to the class/property name and
the message is display anywhere in the description, which makes the doc hard to understand.
Some API documentation were already updated as part of the Typedoc version dump, but some remains unchanged. This is now
fixed.
See #2079
before | now
----- | -----
=> [DOC] Improve the doc of API marked as experimental in the HTML docs

test/unit/component/parser/json/BpmnJsonParser.event.test.ts, test/unit/helpers/bpmn-model-expect.ts
- Simplify how to set the expected values as parameter in the tests for event.
- Also, I change the way to check the type of the flowNode shape.
We should verify the type of the instance of the result with the expected type, and not the contrary.
It's the first step to simplify the event tests. To see the final result, see #2098.
=> [REFACTOR] Move 'verify shape' function for event in utils file

test/unit/component/parser/json/BpmnJsonParser.event.test.ts, test/unit/helpers/JsonBuilder.test.ts, test/unit/helpers/JsonBuilder.ts
- Introduce BuildDefinitionParameter & BuildExclusiveGatewayParameter interface
- Add option to add Participant in the generated json
It's the second step to simplify the unit tests of the JsonParser. To see the final result, see https://github.com/process-analytics/bpmn-visualization-js/pull/2098.
=> [TEST] Add option to add Participant on JsonBuilder

test/unit/component/parser/json/BpmnJsonParser.event.test.ts, test/unit/helpers/JsonBuilder.test.ts, test/unit/helpers/JsonBuilder.ts
- Introduce BuildTaskParameter interface
- Modify the option to add task in order to customize it and add several
It's the 3rd step to simplify the unit tests of the JsonParser. To see the final result, see https://github.com/process-analytics/bpmn-visualization-js/pull/2098.
=> [TEST] Customize Task in generated json by JsonBuilder 

test/unit/helpers/JsonBuilder.test.ts, test/unit/helpers/JsonBuilder.ts
Modify the option in JsonBuilder to add several exclusiveGateway.
Depends on https://github.com/process-analytics/bpmn-visualization-js/pull/2101
It's the 4th step to simplify the unit tests of the JsonParser. To see the final result, see https://github.com/process-analytics/bpmn-visualization-js/pull/2098.
=> [TEST] Add several Exclusive Gateway in generated json by JsonBuilder

test/unit/helpers/JsonBuilder.test.ts, test/unit/helpers/JsonBuilder.ts
- Introduce BuildCallActivityParameter interface
- Add option to add several callActivity in the generated json
Depends on https://github.com/process-analytics/bpmn-visualization-js/pull/2102
It's the 5th step to simplify the unit tests of the JsonParser. To see the final result, see https://github.com/process-analytics/bpmn-visualization-js/pull/2098.
=> [TEST] Add several Call Activity in generated json by JsonBuilder

test/unit/helpers/JsonBuilder.test.ts, test/unit/helpers/JsonBuilder.ts
- Introduce BuildMessageFlowParameter interface
- Add option to add several message flows in the generated json
Depends on https://github.com/process-analytics/bpmn-visualization-js/pull/2103
It's the 6th step to simplify the unit tests of the JsonParser. To see the final result, see https://github.com/process-analytics/bpmn-visualization-js/pull/2098.
=> [TEST] Add several Message Flow in generated json by JsonBuilder

test/unit/component/parser/json/BpmnJsonParser.event.test.ts, test/unit/helpers/JsonBuilder.test.ts, test/unit/helpers/JsonBuilder.ts
- Remove `index` option from `BuildEventParameter`. The id of the event is now automatically calculated with its index on the array on `BuildProcessParameter`.
- Merge all options of `events` on `BuildProcessParameter` into the `BuildEventParameter` interface.
- Rename `events` of `BuildProcessParameter` in `event` and change its type by `BuildEventParameter` or `BuildEventParameter[]`
Depends on https://github.com/process-analytics/bpmn-visualization-js/pull/2104
It's the 7th step to simplify the unit tests of the JsonParser. To see the final result, see https://github.com/process-analytics/bpmn-visualization-js/pull/2098.
=> [TEST] Change the way to build an event with JsonBuilder

test/unit/component/parser/json/BpmnJsonParser.messageFlow.test.ts, test/unit/helpers/JsonBuilder.test.ts, test/unit/helpers/JsonBuilder.ts
Closes #2041  
- Add an option on `JsonBuilder` to override the default id of the generated event
- New unit tests
- Fix unit tests for `message flow` with source/target as `Event`
=> [TEST] To be able to override the generic id of the generated event with JsonBuilder

.github/release-drafter.yml
Avoid forgetting to delete the reminder comments and not updating the full changelog link.
This is what we have done manually in https://github.com/process-analytics/bpmn-visualization-js/releases/tag/v0.26.0
To be first tested with https://github.com/process-analytics/github-actions-playground/pull/123
=>  [INFRA] Improve full changelog visibility in release notes

.github/dependabot.yml, .github/release-drafter.yml
Dependabot now creates Pull Requests that are not present in the release notes.
As there is only runtime dependencies in the release notes, the dependency updates list isn't collapsed to ensure all
changes are visible.
The `Dependencies update` section is now above the `Maintenance` section as dependencies update are more important for
users than what we did internally to improve the library.
Other release notes improvements:
- exclude process-analytics-bot. The project bot is excluded from the $CONTRIBUTORS variable to avoid manual edits of
the release notes.
- update after label changes in the GitHub repository
- infra:refactoring --> refactoring
- infra:build --> chore
- infra:repo: removed
closes #2208
The updated dependabot configuration has already been tested: 
- configuration: …
=> [DOC] Do not add dev dependencies to release notes

CHANGELOG.md
This allows people who are used to reading changelog files to know where to find the `bpmn-visualization` release notes.
Inspiration
- https://github.com/ezolenko/rollup-plugin-typescript2/blob/0.34.0/CHANGELOG.md
- https://github.com/agilgur5/react-signature-canvas/blob/v1.0.6/CHANGELOG.md
=> [DOC] Add a changelog file that refs GH releases

docs/users/intro.adoc
We removed reference to the " early development stage" in the README. Do the same in the user documentation.
This change was first proposed in #2184 
Change in README: #1869
=> [DOC] Simplify the introduction of the user documentation

src/component/registry/bpmn-model-filters.ts
This is an internal implementation which references the `BpmnModel` type. As `BpmnModel` is internal as well and is not exported, it cannot be resolved which generates type errors.
The issue can be seen in https://unpkg.com/browse/bpmn-visualization@0.26.1/dist/component/registry/bpmn-model-filters.d.ts
Notice that the API doc doesn't include the `ModelFiltering` class. Implementing #2231 will probably fix any future issue of that kind.
Tested by running `tsc --emitDeclarationOnly --declaration --project ./tsconfig.bundle.json`
For reviews: check the content of the npm package generated by the related Checks on this PR.
=> [FIX] Do not export ModelFiltering in types

package.json, rollup.config.js
The browser field is meant to declare module that are used client-side.
We previously set its value to the IIFE bundle which cannot be used for
such purpose.
closes #2228
=> [FIX] Fix the browser field in package.json

README.md
Put the information in the README. This is a first step of larger changes that will be implemented later.
Making it explicit in the README is just a minimum.
refs #2246
=> [DOC] README indicates the lowest supported TypeScript version

test/integration/dom.css.classes.test.ts, test/unit/component/registry/css-registry.test.ts
This is not documented and sometimes works as if several strings were passed in the CSS classes array (for add only).
The tests just show the actual behavior, not how the code should behave.
We discovered the actual behavior by accident while working on some demos.
=> [TEST] Add more tests when passing CSS classes separated by spaces

.github/workflows/build.yml, .github/workflows/generate-demo-preview.yml, .github/workflows/test-e2e.yml, .github/workflows/upload-npm-package.yml
Currently, across the whole GitHub organization, we can run at most 20 jobs simultaneously and no more than 5 in parallel on macOS. To reduce the load, let's reduce the amount of jobs that are run when pushing in the bpmn-visualization repostiory.
The main change here is to stop running bundle tests on all OS with all browsers. This drops 11 jobs for each PR that runs the 'build' workflow! The bundle tests are now run in the workflow that build and upload the npm package.
Other configurations of workflows have been updated to not run when some files not involved in the workflow run are modified.
covers #2172
=> [INFRA] Run some GH workflows less often

dev/public/elements-identification.html, dev/public/static/js/elements-identification.js, dev/ts/component/DropFileUserInterface.ts, dev/ts/main.ts, src/component/registry/bpmn-elements-registry.ts, src/component/registry/query-selectors.ts, test/e2e/helpers/visu/bpmn-page-utils.ts, test/helpers/query-selectors.ts, test/integration/BpmnVisualization.test.ts, test/integration/dom.bpmn.elements.test.ts, test/integration/dom.container.div.test.ts, test/integration/dom.css.classes.test.ts, test/integration/dom.overlays.test.ts, test/integration/helpers/bpmn-visualization-initialization.ts, test/integration/helpers/dom-utils.ts, test/integration/helpers/html-utils.ts
Previously, calling `BpmnElementsRegistry.getElementsByIds` generated error when the HTML BPMN container has no id.
When using framework like Svelte or Angular, the container doesn't have such id, so it prevented to use the API out of the box.
The CSS selector that retrieves the HTML elements has been simplified to not use the id. 
The "elements-identification" demo has been updated to use a BPMN container without id.
Prior, the fix, it reproduced the issue when calling the registry API
```
ERROR DOMException: Document.querySelector: '# > svg > g > g > g[data-bpmn-id="Activity_1potg3p"]' is not a valid selector
```
The drag'n drop code was only able to manage container with id. It has been updated to support container without id as well.
Closes #2270 
The bug is reproduced with the first …
=> [FIX] Allow BPMN container HTML element without id

NOTICE, package.json
Remove extra TSDoc syntax, only keep plain text.
The NOTICE file has been excluded from the eslint processing: this file doesn't change, is related to the documentation, and does not follow the JS/TS header file format. So there is no reason to lint it.
Restore the Copyright date to `2020`. This is the start date of the project.
This PR is based on the work done for the website: https://github.com/process-analytics/process-analytics.dev/pull/706
The NOTICE file initially mention year 2020. #1957 changed it to 2022. We now restore it to its initial value 😸
=> [DOC] Simplify the content of the NOTICE file

.github/workflows/upload-npm-package.yml, config/api-extractor.json, package-lock.json, package.json, scripts/generate-types-for-not-supported-ts-versions.mjs, src/component/mxgraph/initializer.ts, test/bundles/bundles.test.ts, test/bundles/jest.config.js, test/bundles/npm.package.test.ts, tsconfig.npm-package.json
The file is generated thanks to `api-extractor` which use the types generated by `tsc` to build a single file including all types.
This is more consistent with the ESM bundle: we now have a single file for both types and ESM in the npm package, and the internal layout of the sources is not exposed externally.
As a bonus, it removes extra types that were erroneously available in the npm package (JSON model types).
The bundle tests have been divided with a file that tests the display in an HTML page using the IIFE bundle and a file that checks the files available in the npm package.
For the later, the checks are stricter than before. They expect an exact list of files instead of just checking that some files are present (it missed extra files).
Note that the types now export an extra …
=> [REFACTOR] Include a single file for types in the npm package

README.md, package.json, scripts/generate-types-for-not-supported-ts-versions.mjs, test/typescript-support/package.json
Explicitly support version greater or equal to 4.0.2 (first GA version of the 4.0 line). The README now explains what was the version supported for older releases of `bpmn-visualization`. It shows the progress and will help people using old versions to not be misguided when looking the documentation directly from the GitHub Web UI or the README of the `master` branch.
In addition, update the types file included in the npm package and used when the TypeScript version is not supported. It now contains a comment explaining what this file does.
closes #2221
closes #2252
Based on POC done for #2230
The information about the TS version supported by v0.17.1 is taken from #1415
Tested locally and with https://github.com/process-analytics/bpmn-visualization-examples/pull/418
=> [FEAT] Downlevel the minimum supported TS version from 4.5 to 4.0

README.md
Hacktoberfest is finished, so use the regular image.
The Hacktoberfest image in the README was introduced in #2275
=> [DOC] Revert Hacktoberfest hero image from the README

.github/actions/custom-surge-preview/action.yml
The new release removes warnings.
https://github.com/bonitasoft/actions/releases/tag/v2.0.0
=> [INFRA] gha - bump surge-preview-tools from v1 to v2

.github/actions/install-playwright-browser/action.yml, .github/workflows/test-e2e.yml, .github/workflows/test-performance.yml, .github/workflows/upload-npm-package.yml, src/component/mxgraph/renderer/StyleComputer.ts
Previously, we installed Chrome and MSEdge prior running the tests whereas the browsers are already installed in the GitHub runners.
This increases build time and limit build reproducibility (the available version for download can change without notice).
Introduce an action to manage browser download logic, in particular, to decide whether to download the browser. This will help in the future if we want to cache browsers downloaded by playwright itself.
closes #2355
covers #2356
✔️ e2e reports are correctly generated in case of error. See 2cf18f1
✔️ all tests pass
=> [INFRA] Use chrome/edge installed in GitHub runners

src/component/mxgraph/config/StyleConfigurator.ts
Shape: move the "arc size" configuration to the default vertex style:
- This avoids duplication in specific styles
- The configuration is now inherited from the default style, so it is easier to change it. Just change it on the default, and it will be applied automatically to all vertices
Default edge rounded settings: used boolean instead of number for consistency. Boolean are used everywhere else.
Shared `configureCommonDefaultStyle` function:
- Call it in first. This lets override any values it defines in specific default edge and vertex configuration.
- Move it out of the class as it doesn't depend on any values and properties of this class
=> [REFACTOR] Improve the default style configuration

src/component/mxgraph/config/StyleConfigurator.ts
In all `AssociationDirectionKind` styles, add configurations for end and start arrow, instead of removing it. This is consistent with the rest of the configuration and make the configuration easier to follow.
Also introduce a constant to have same size by default for all end and start arrows. This avoids the use of the magic number several times. Instead, the constant with a convenient name makes the configuration clearer.
=> [REFACTOR] Clarify the style configuration for `Associations`

.github/workflows/announce-new-release.yml, .github/workflows/build.yml, .github/workflows/codeql-analysis.yml, .github/workflows/dependency-review-pr.yml, .github/workflows/fill-gh-draft-release.yml, .github/workflows/generate-demo-preview.yml, .github/workflows/generate-documentation.yml, .github/workflows/publish-npm.yml, .github/workflows/release.yml, .github/workflows/test-e2e.yml, .github/workflows/test-performance.yml, .github/workflows/upload-demo-archive-and-trigger-examples-repository-update.yml, .github/workflows/upload-npm-package.yml
This reverts commit 49315fa7136776a29053b6724f867329a919a5b7.
Configuration variables are currently not passed to workflows that are triggered by a pull request from a fork and from dependabot.
This revers #2465 
For discussions about the current _Configuration Variables_ limitations, see 
- https://github.com/orgs/community/discussions/44088
- https://github.com/orgs/community/discussions/44322
=> [INFRA] Revert "use organization variables for runners"

.github/workflows/test-npm-package.yml
The former name was misleading. The workflow does not upload the package to a shared repository/package. The generated package is uploaded as a GH action artifact for convenience, but it cannot be consumed by a Node package manager.
=> [INFRA] Rename the GH workflow that build and test the npm package

src/bpmn-visualization.ts, src/component/mxgraph/initializer.ts
Also remove the mxgraph import in main ts file as it is not needed.
closes #2480 
IIFE minified: minimal impact
For other bundles, the increase is mainly due to the comments attached to the new exported `mxgraph` element. This will slightly increase the overall size of the npm package, but this won't have impact for applications integrating `bpmn-visualization`.
#2489 will reduce the impact of the change in this PR.  
bundle name | master eb092f1 | this PR
---- | ---- | ----
bpmn-visualization.d.ts | 42 153 | 42 626
bpmn-visualization.esm.js | 266 241 | 266 729
bpmn-visualization.js | 2 915 673 | 2 916 207
bpmn-visualization.min.js | 982 8**46** | 982 8**70**
not-supported-ts-versions.d.ts | 368 | 368
See https://github.com/process-analytics/bpmn-visualization-examples/pull/449
=> [FEAT] Export the mxgraph context

src/component/registry/bpmn-model-registry.ts, src/component/registry/types.ts, test/integration/dom.bpmn.elements.test.ts, test/integration/helpers/semantic-with-svg-utils.ts, test/unit/component/registry/bpmn-model-registry.test.ts, test/unit/helpers/bpmn-model-utils.ts, test/unit/helpers/bpmn-semantic-utils.ts
This will facilitate the implementation of "path-related" use cases.
BREAKING CHANGES:  the `BpmnSemantic` type includes new properties that are mandatory.
closes #2504
=> [FEAT] BpmnElementsRegistry API returns shape incoming/outgoing

src/component/parser/json/converter/ProcessConverter.ts
This hides new TypeScript errors which can be silently added when the file is updated. Instead, disable the rule on each line.
Detected while implementing #2525
=> [REFACTOR] Do not ignore the 'ban-ts-comment' eslint rule per file

package.json, rollup.config.mjs, scripts/add-license-header.mjs, scripts/generate-types-for-not-supported-ts-versions.mjs, scripts/shared/banner.mjs, scripts/shared/types-info.mjs
This applies to JavaScript files and type definition files.
The headers are created using the same template as used for the source files. The minified IIFE bundle receives a specific header to reduce the size of the added content.
covers #2489
Total increase: 2508
Remember that there will be other changes as part of #2489 that will finally decrease the overall size of the package
file | master e16eaf2 | PR 2524 | diff
------ | ------ | ------ | ------
bpmn-visualization.d.ts | 43 249 | 43 851 | 602
bpmn-visualization.esm.js | 267 897 | 268 499 | 602
bpmn-visualization.js | 2 916 667 | 2 917 269 | 602
bpmn-visualization.min.js | 982 739 | 982 839 | 100
not-supported-ts-versions.d.ts | 368 | 970 | 602
The files of the dist folder of the npm package should now all contain the header.
The …
=> [DOC] Add license header to all dist files in npm package

src/component/mxgraph/BpmnGraph.ts, src/component/mxgraph/BpmnRenderer.ts, src/component/mxgraph/GraphConfigurator.ts
This new method in `BpmnGraph` avoids using the try/catch idiom which is replaced by a simple method call.
It is inspired from the related `maxGraph` function.
Also add the model clear within the transaction in `BpmnRenderer`. This increase the overall speed because the model
changes are all "committed" at the same time. We can then expect better overall rendering performance.
In addition, always use the `panningHandler` const in `GraphConfigurator` for consistency with the rest of the code and
to avoid any future side effects.
This has been detected during the `maxGraph@0.1.0` migration POC: #2366 
This will also needed in the future as we are going to use more transactions. See #2539.
=> refactor: introduce `batchUpdate` for model transaction

src/component/mxgraph/renderer/StyleComputer.ts, test/integration/matchers/matcher-utils.ts, test/unit/component/mxgraph/renderer/StyleComputer.test.ts, test/unit/component/mxgraph/renderer/style-utils.test.ts
There was a duplication because the test utility code and the production code do not use the same type to handle the
fonts. The test utility code now calls the production code.
In addition, add missing types in tests function of some unit tests.
maxGraph 0.1.0 migration POC: #2366 
This will also be needed by the style API, see #2539
=> test: remove duplication in font value computation

src/component/mxgraph/renderer/StyleComputer.ts, src/component/mxgraph/renderer/style-utils.ts, src/component/mxgraph/shape/activity-shapes.ts, src/component/mxgraph/shape/event-shapes.ts, src/component/mxgraph/shape/flow-shapes.ts, src/component/mxgraph/shape/gateway-shapes.ts, src/component/mxgraph/shape/render/icon-painter.ts, src/component/mxgraph/style/index.ts, src/component/mxgraph/style/utils.ts, test/integration/matchers/toBeEdge/index.ts, test/unit/component/mxgraph/renderer/StyleComputer.test.ts, test/unit/component/mxgraph/renderer/style-utils.test.ts
Replace `StyleUtils` methods by direct calls: the methods were used only once, so this was an extra indirection (the inline code is explicit enough).
Extract only the `getBpmnIsInstantiating` function because it is used twice and make it internal.
It also changes the way we store `bpmn.isInitiating` in the mxGraph style. Previously, we stored the value from the BPMN Semantic as a string which required a subsequent parsing to know whether it was an "instantiate" value. This was also not consistent with the property name which suggests to store a boolean value.
We now store a boolean value which can be directly used in the Shapes implementation.
--------------------------------------------------------------------------------
BREAKING CHANGES: `StyleUtils` may have been used in rare cases to …
=> refactor: remove StyleUtils

test/fixtures/bpmn/model-complete-semantic.bpmn, test/integration/mxGraph.model.bpmn.elements.test.ts
The message flows did not declare waypoints, so they passed through many shapes. The diagram was not easy to read. These flows now bypass all shapes.
In addition, a message flow wasn't displayed because of a bad id set in its targetRef. 
Also invert source and target
Detected during #2539 
before | now
---- | ----
Here is the diagram, before the display of the missing flow nodes (55b610b).
=> test: improve the layout of the integration test BPMN Diagram

dev/public/bpmn-rendering.html, dev/public/static/js/bpmn-rendering.js, dev/public/static/js/diagram-navigation.js, dev/public/static/js/elements-identification.js, dev/public/static/js/index.js, dev/public/static/js/overlays.js, dev/ts/main.ts, dev/ts/utils/internal-helpers.ts, dev/ts/utils/shared-helpers.ts, test/e2e/helpers/visu/bpmn-page-utils.ts
The tests were previously blocked if a fetch diagram error occurred. A `window alert` appeared, which prevented Playwright from interacting with the browser afterwards (for retries and subsequent test runs).
As part of the fix:
- add logs to improve troubleshooting
- do not display `window alert` in test pages when an error occurs on diagram fetch ("diagram-navigation.html" and "overlays.html"). This blocked the browser and all following tests finished in error (Playwright is unable to interact with the page).
- also avoid `window alert` on BPMN load error in the test pages.
- change the error management to only log errors by default. If a new page is created, it won't use `window alert` by mistake.
Fetch errors can occur but this is not an issue as we configure jest retries. Generally, …
=> ci(e2e-tests): fix false positive tests on macOS with Firefox

test/unit/component/parser/json/BpmnJsonParser.callActivity.test.ts, test/unit/component/parser/json/BpmnJsonParser.event.test.ts, test/unit/component/parser/json/BpmnJsonParser.group.test.ts, test/unit/component/parser/json/BpmnJsonParser.lane.test.ts, test/unit/component/parser/json/BpmnJsonParser.process.test.ts
The default value of `parentId` of `ExpectedShape` and `ExpectedEdge` is `undefined`, so no need to specify it, to make the tests more readable.
=> test: remove unnecessary attribute check in json parsing tests

dev/public/elements-identification.html, dev/public/static/js/elements-identification.js, dev/ts/main.ts, src/component/registry/types.ts
- Export missing type for the API documentation : `StyleWithOpacity`
- Add a radio button to select the mode to apply the style: CSS or API
- Update the style according the selected BPMN kind and the style method (CSS or API). 
When switching from CSS to API, the CSS class applied to the selected BPMN kind are cleared.
- Introduce new function in the `main` JS file for `Elements Identification` demo, to style without parameters: `updateStyle`
Closes #2558
=> feat: use the "Update Style" API in the "Elements Identification" demo

test/unit/component/parser/json/BpmnJsonParser.sub.process.test.ts, test/unit/helpers/JsonBuilder.test.ts, test/unit/helpers/JsonBuilder.ts
- Improve the test helper `JsonBuilder` for the Sub-Process 
- Generate json containing `subProcess` related to a `Shape` with `isExpanded` attribute
- Generate json containing `subProcess`  with `triggeredByEvent` attribute
- Generate json containing `subProcess`  with `incoming` attribute
- Generate json containing `subProcess`  with `outgoing` attribute
- Use the test helper `JsonBuilder` in the unit tests for `BpmnJsonParser` with `subProcess`
=> test: improve JsonBuilder for the Sub-Process

test/unit/component/parser/json/BpmnJsonParser.association.test.ts, test/unit/component/parser/json/BpmnJsonParser.sub.process.test.ts, test/unit/helpers/JsonBuilder.test.ts, test/unit/helpers/JsonBuilder.ts
- Improve the test helper `JsonBuilder` to generate a JSON containing `association`
- Use the test helper `JsonBuilder` in the unit tests for `BpmnJsonParser` with `association`
=> test: improve JsonBuilder for the Association

test/unit/component/parser/json/BpmnJsonParser.callActivity.test.ts, test/unit/helpers/JsonBuilder.test.ts, test/unit/helpers/JsonBuilder.ts, test/unit/helpers/bpmn-model-expect.ts
- Improve the test helper `JsonBuilder` to generate a JSON containing `global task`
- Use the test helper `JsonBuilder` in the unit tests for `BpmnJsonParser` with `global task` and `call activity`
- Fix the test verifier for call activity
=> test: improve JsonBuilder for `global task` and `call activity`

test/unit/component/parser/json/BpmnJsonParser.sub.process.test.ts, test/unit/component/parser/json/BpmnJsonParser.text.annotation.test.ts, test/unit/helpers/JsonBuilder.test.ts, test/unit/helpers/JsonBuilder.ts
- Improve the test helper `JsonBuilder` to generate a JSON containing `textAnnotation`
- Use the test helper `JsonBuilder` in the unit tests for `BpmnJsonParser` with `textAnnotation`
- Add missing unit test for `BpmnJsonParser` with `subProcess` containing `textAnnotation`
=> test: improve JsonBuilder for the Text Annotation

src/component/mxgraph/GraphCellUpdater.ts
Remove duplication
- simplify the handling of boolean font properties by introducing a convenient `setStyleFlag` function.
- simplify string properties management by introducing the  `setStyle` function.
Detected while developing https://github.com/process-analytics/bpmn-visualization-js/pull/2585#pullrequestreview-1345638798
> The IDEs pop duplication warnings on this and I should have also introduced the same function for the regular "setStyle" call. Having a guard to check if the variable is defined prior the function call is a big duplication and make the code hard to read.
=> refactor: remove duplication in the "Update Style" API

.github/workflows/publish-npm.yml
This beta feature let users know how the package was published. In our case, the package page will display that it is done using GitHub Actions.
Resources
- https://github.blog/changelog/2023-04-19-npm-provenance-public-beta]
- https://docs.npmjs.com/generating-provenance-statements
The publish provenance options is available in the recent npm version, in particular the version used by GH actions
- npm cli documentation: https://docs.npmjs.com/cli/v9/commands/npm-publish
- recent run of GH Actions https://github.com/process-analytics/bpmn-visualization-js/actions/runs/4822107411/jobs/8588897848?pr=2467 
```
Run actions/setup-node@v3
Resolved .nvmrc as 18
Found in cache @ /opt/hostedtoolcache/node/18.16.0/x64
Environment details
node: v18.16.0
npm: 9.5.1
yarn: 1.22.19
```
Local check of …
=> ci: publish npm package with "provenance"

src/component/helpers/validators.ts, src/component/mxgraph/config/ShapeConfigurator.ts, src/component/parser/json/converter/DiagramConverter.ts
- Prefer using nullish coalescing operator (`??`) instead of a ternary expression, as it is simpler to read.
- Prefer using an optional chain expression instead, as it's more concise and easier to read.
The issues have not been introduced recently. The TypeScript profile has been updated yesterday with new rules.
The remaining issues are mainly due to the misuse of `enum`. The places were the issues occur are clearly subject to removal (for instance `StyleDefault`). We don't need enum for structures that store data that are not intended to be enumerated.
=> refactor: fix code smells detected by SonarCloud

.github/release-drafter.yml
We often forget to mention changes in the `examples` repository in the release notes. So, update the `release-drafter` template to guide the writers.
This occured in the 0.34.0 release notes: https://github.com/process-analytics/bpmn-visualization-examples/releases/tag/v0.34.0
In this case, we try to make up for the omission in the following notes but it requires extra work not to forget.
These tips will result in better documentation and less work for the maintainers.
=> docs(release): add tips for referencing the `examples` repository

src/component/registry/types.ts
This pull request proposes a change to the **Overlay** types. 
Previously, these types were defined as `interface`. The changes suggests moving them to `type` aliases, aligning with TypeScript's philosophy. This change does not affect the API contract and is aimed at providing a better match to the intended usage of the structures, and a consistent declaration with the `StyleUpdate` type.
1st proposed in #2673
According to the TypeScript documentation on ["Differences Between Type Aliases and Interfaces"](https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#differences-between-type-aliases-and-interfaces), the main distinction is that types cannot be extended. 
By using `type` aliases instead of `interface`, we ensure that the **Overlay** types are appropriate for their …
=> refactor: transform overlay types from interface to type

src/component/mxgraph/GraphCellUpdater.ts, src/component/mxgraph/config/ShapeConfigurator.ts, test/integration/helpers/model-expect.ts, test/integration/matchers/matcher-utils.ts, test/integration/mxGraph.model.css.api.test.ts, test/integration/mxGraph.model.style.api.test.ts
Previously, calling the "Update Style" API after the adding classes with CSS API removed the CSS classes from a given BPMN element.
This is now fixed by setting the classes in the model instead of updating directly the state. The state is refreshed when calling the "Update Style" API and the manually added classes were removed.
Basic integration tests have been added to check that the CSS classes are present in the style property of the mxGraph model. They only check a few use cases to help detecting regression They complement the existing tests checking that the classes are correctly set in the SVG nodes. The existing tests cover all use cases of the CSS API.
closes #2561
=> fix: keep existing CSS classes when calling the "Update Style" API

.github/workflows/test-performance.yml
It was previously run when any test diagram was changed. This occurs quite often when implementing new features whereas the performance tests don't use them.
Covers #2172
=> ci: run the "performance test" workflow less often

package-lock.json, package.json
https://github.com/typed-mxgraph/typed-mxgraph/releases/tag/v1.0.8
=> chore(deps): bump @typed-mxgraph/typed-mxgraph from 1.0.7 to 1.0.8

dev/ts/component/SvgExporter.ts, dev/ts/component/ThemedBpmnVisualization.ts, src/component/mxgraph/BpmnGraph.ts, src/component/mxgraph/BpmnRenderer.ts, src/component/mxgraph/GraphCellUpdater.ts, src/component/mxgraph/GraphConfigurator.ts, src/component/mxgraph/config/ShapeConfigurator.ts, src/component/mxgraph/config/StyleConfigurator.ts, src/component/mxgraph/initializer.ts, src/component/mxgraph/overlay/custom-overlay.ts, src/component/mxgraph/renderer/CoordinatesTranslator.ts, src/component/mxgraph/renderer/StyleComputer.ts, src/component/mxgraph/shape/activity-shapes.ts, src/component/mxgraph/shape/edges.ts, src/component/mxgraph/shape/event-shapes.ts, src/component/mxgraph/shape/flow-shapes.ts, src/component/mxgraph/shape/gateway-shapes.ts, src/component/mxgraph/shape/render/icon-painter.ts, src/component/mxgraph/shape/text-annotation-shapes.ts, src/component/mxgraph/style/utils.ts, src/component/version.ts, test/integration/config/mxgraph-config.ts, test/integration/matchers/toBeEdge/index.ts, test/integration/matchers/toBeShape/index.ts, test/integration/mxGraph.model.bpmn.elements.test.ts
The mxGraph initializer module now exports main mxGraph objects that are used several times in the library. This make the code easier to read and reduce the size of minified bundles.
So, when used, there is no more need to prefix the call of mxGraph object by mxgraph. For instance, instead of writing `mxgraph.mxConstants.XXX`, it is possible to write `mxConstants.XXX`.
Notice that in files where both values (from mxGraph) and types (from typed-mxgraph) are imported, the types are aliased to avoid name clash. The convention taken is to postfix the type by `Type` to make it explicit.
Refactoring detected during #2366 
Size decrease in the minified IIFE bundle: 1554b / 1.51kb
master: 3d36ba70708be4fdc8a4e6242ac2e840758a33f0
file | before | after
---- | ---- | ----
bpmn-visualization.esm.js | …
=> refactor: directly use mxGraph value objects

.github/dependabot.yml
Configure the new beta `groups` options to update development dependencies by group of features.
This reduces the number of Pull Requests to be reviewed  and ensure that related dependencies are updated at the same time.
closes #2511 
Validated with https://github.com/tbouffard/experiment-dependabot-groups.
This is the same configuration as in the test repository expect the `eslint` group which has been renamed (and then moved to keep alphabetic order) into `lint` (more general as it also includes prettier and other libs.
- https://github.blog/changelog/2023-06-30-grouped-version-updates-for-dependabot-public-beta/
- https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups
=> chore(dependabot): groups dependencies

src/component/mxgraph/GraphCellUpdater.ts, src/component/registry/bpmn-elements-registry.ts, test/integration/jest.config.js, test/integration/mxGraph.model.css.api.test.ts, test/integration/mxGraph.model.style.api.test.ts
Previously, passing an empty array acts like passing a nullish parameter. The style of all elements was reset.
Also update the JSDoc of some methods of `BpmnElementsRegistry` to clarify what exactly happen when passing nullish or empty array as parameter for the ids of the BPMN elements. Create the corresponding integration tests to confirm the actual behavior.
covers https://github.com/process-analytics/bv-experimental-add-ons/issues/67
=> fix: reset the style of elements only when passing nullish param

.github/workflows/announce-new-release.yml, docs/contributors/maintainers.md
It is no longer possible to post a tweet with the API without a paid plan (and we only have a free plan). So, remove the automation and documentation how to do it manually.
closes #2676
=> chore(release): publish announce tweet manually

src/component/parser/json/converter/ProcessConverter.ts, test/unit/component/parser/json/BpmnJsonParser.association.test.ts, test/unit/component/parser/json/BpmnJsonParser.edge.test.ts, test/unit/component/parser/json/BpmnJsonParser.flowNode.test.ts, test/unit/component/parser/json/BpmnJsonParser.group.test.ts, test/unit/component/parser/json/BpmnJsonParser.label.bounds.test.ts, test/unit/component/parser/json/BpmnJsonParser.label.font.test.ts, test/unit/component/parser/json/BpmnJsonParser.label.test.ts, test/unit/component/parser/json/BpmnJsonParser.lane.test.ts, test/unit/component/parser/json/BpmnJsonParser.marker.test.ts, test/unit/component/parser/json/BpmnJsonParser.messageFlow.test.ts, test/unit/component/parser/json/BpmnJsonParser.process.test.ts, test/unit/component/parser/json/BpmnJsonParser.sequenceFlow.conditional.test.ts, test/unit/component/parser/json/BpmnJsonParser.sequenceFlow.default.test.ts, test/unit/component/parser/json/BpmnJsonParser.sequenceFlow.normal.test.ts, test/unit/component/parser/json/BpmnJsonParser.sub.process.test.ts
This pull request makes three improvements to `JsonParser` and its associated unit tests:
- Enforce the `BpmnJsonModel` type for the JsonParser dataset in the unit tests: This is a first step in addressing issue #2188.
This enforcement ensures that the JSON passed to the parser adheres to the required format. 
ℹ️ It's worth noting that I have observed cases where TypeScript failed to detect incorrect JSON formats when the type was not explicitly set.
- Simplified JSON data initialization for `JsonParser` unit tests: This makes our test code more readable and easier to maintain.
- Detection of the TypeScript-based `default` property of `TProcess` in the `ProcessConverter`.
These improvements enhance code reliability, readability and accuracy.
=> test: refactor JsonParser unit tests and type handling enhancements

src/component/mxgraph/shape/edges.ts, src/component/mxgraph/shape/flow-shapes.ts
They were located in mxGraph custom shapes.
This has been detected by SonarCloud with rule `typescript:S6647`.
"If the class declaration does not include a constructor, one is automatically created, so there is no need to provide an empty constructor, or one that just delegates to the parent class."
These new Code Smells have been recently detected after the builtin Quality Profiles were updated with new rules.
=> refactor: remove extra constructors

.github/actions/build-setup/action.yml
It had been removed because an issue `jest-playwright` that is now marked as resolved.
https://github.com/playwright-community/jest-playwright/issues/808#issuecomment-1304862603
=> ci: restore "--ignore-scripts" option for `npm ci`

src/component/parser/json/converter/EventDefinitionConverter.ts, src/component/parser/json/converter/ProcessConverter.ts, src/model/bpmn/json/BPMN20.ts, src/model/bpmn/json/baseElement/rootElement/rootElement.ts, test/unit/component/parser/json/BpmnJsonParser.flowNode.test.ts, test/unit/component/parser/json/BpmnJsonParser.lane.test.ts, test/unit/component/parser/json/BpmnJsonParser.marker.test.ts, test/unit/helpers/JsonBuilder.ts
1.  **Fix in `TProcess` parsing:** Removed unnecessary parsing of `lane` elements of the `TProcess` type that are not specified in the BPMN specification. This ensures correct parsing behavior.
2.  **Property removal:** The `[key: string]: any;` property has been removed from both the `TProcess` and `TDefinitions` classes. This prevents inadvertent access to non-existent properties within these objects.
3.  **JSONBuilder Function Renaming and Enhancement:** Renamed the `updateBpmnElement` function within the `JSONBuilder` class for better clarity. The function code has also been streamlined to improve readability and comprehension.
Closes #2188
=> fix: remove extra parsing of lane elements which are not in the BPMN spec

test/e2e/bpmn.colors.test.ts, test/e2e/bpmn.elements.collapsed.test.ts, test/e2e/bpmn.elements.filter.pools.test.ts, test/e2e/bpmn.rendering.test.ts, test/e2e/bpmn.theme.test.ts, test/e2e/diagram.navigation.fit.test.ts, test/e2e/diagram.navigation.zoom.pan.test.ts, test/e2e/overlays.rendering.test.ts, test/e2e/style.api.test.ts
A lot of e2e tests failed in local on macOS (13.5.1) due to low threshold configuration.
To avoid to list all files, I increased the global threshold too.
=> test(e2e): fix e2e thresholds on macOS

dev/ts/pages/elements-identification.ts, test/bundles/bundles.test.ts, test/e2e/bpmn.colors.test.ts, test/e2e/bpmn.elements.collapsed.test.ts, test/e2e/bpmn.elements.filter.pools.test.ts, test/e2e/bpmn.rendering.test.ts, test/e2e/bpmn.theme.test.ts, test/e2e/diagram.navigation.fit.test.ts, test/e2e/diagram.navigation.zoom.pan.test.ts, test/e2e/generated.svg.test.ts, test/e2e/overlays.rendering.test.ts, test/e2e/style.api.test.ts, test/integration/matchers/toBeEdge/index.ts, test/performance/bpmn.load.performance.test.ts, test/performance/bpmn.navigation.performance.test.ts, test/shared/visu/bpmn-page-utils.ts, test/unit/helpers/JsonTestUtils.ts, test/unit/helpers/bpmn-model-expect.ts
By including the `@typescript-eslint/recommended-type-checked` rule in pull request #2812, we identify some unnecessary type casting.
Covers #2742
=> refactor: remove unnecessary type casting

package-lock.json, package.json, test/.eslintrc.js, test/performance/bpmn.load.performance.test.ts, test/performance/bpmn.navigation.performance.test.ts, test/unit/component/registry/bpmn-model-registry.test.ts
This pull request introduces changes to enhance the code quality and maintainability of the project. 
- Added `eslint-plugin-jest-extended` as a development dependency.
- Updated the ESLint configuration for the test files to use the rules of `eslint-plugin-jest-extended`.
- Fixed linting issues detected by `eslint-plugin-jest-extended`.
Covers #2742
=> chore(eslint): use `eslint-plugin-jest-extended`

.github/dependabot.yml
Create a new _typescript_ group:
- Group `typedoc` and `typescript` together because `typedoc` supports a specific range of TypeScript versions.
- Switching from TypeScript to a minor or major version alone breaks `npm install` because the current version of `typedoc` doesn't support it.
Update the _jest_ group:
- add `expect-playwright` that was missing
#2829 shows the problem with TypeScript dependencies.
=> chore(dependabot): improve groups configuration

dev/ts/pages/index.ts, dev/ts/shared/main.ts, src/component/helpers/validators.ts, src/component/parser/json/converter/ProcessConverter.ts, test/e2e/helpers/visu/image-snapshot-config.ts, test/performance/helpers/metrics-chromium.ts, test/unit/helpers/bpmn-model-expect.ts
Resolved the error reported by `plugin:@typescript-eslint/stylistic-type-checked` rules by replacing the logical OR (`||`) operator with the nullish coalescing operator (`??`). 
This change contributes to safer and more predictable code behavior, aligning with the recommendations of `@typescript-eslint/prefer-nullish-coalescing`.
=> refactor: improving code safety with nullish coalescing operator

dev/ts/pages/elements-identification.ts, dev/ts/shared/main.ts, src/component/registry/bpmn-elements-registry.ts, src/component/registry/types.ts, test/integration/model.elements.api.test.ts, test/shared/model/bpmn-semantic-utils.ts
Complement the existing method that also retrieves DOM information. This simplifies the API usage and reduce the amount of retrieved data when the caller only needs to get the information from the model.
In addition:
- Simplify the existing `getElementsByKinds` implementation: use a flat array instead of an array of array. This is then also consistent with the implementation of the new method.
- Use the new API in demo to simplify the code.
- Rework the existing JSDoc for consistency
closes #2813
=> feat: add a method to only get BPMN semantic of elements by kind

.github/workflows/release.yml
The workflow commits to the main branch and the branch protection configured in the GitHub repository prevents this for all users.
Previously, the protection was temporarily bypassed and the user performing the commit required administrator permissions (due to the configuration of the branch protection).
Now protection is done using GitHub branch ruleset, and there's no need to bypass protection. In this way, workflow can be simplified.
The settings have already been updated
- rulesets replaces branch and tag protection: https://github.com/process-analytics/bpmn-visualization-js/rules (publicly visible)
repository
- permissions of the user performing the Git operations in the repository has been downgraded. ⚠️ **IMPORTANT**: this PR must then be merged prior doing the next release. The …
=> ci(release): eliminate bypassing of branch protection

.eslintrc.cjs, dev/ts/component/DropFileUserInterface.ts, dev/ts/pages/bpmn-rendering.ts, dev/ts/pages/diagram-navigation.ts, dev/ts/pages/elements-identification.ts, dev/ts/pages/index.ts, dev/ts/pages/overlays.ts, dev/ts/shared/controls.ts, src/component/helpers/dom-utils.ts
To avoid to have to many changes by enabling `plugin:unicorn/recommended`, I choose to enable some rule one-by-one.
https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prefer-query-selector.md
Part of #2824
Covers #2742
=> chore(eslint): add `unicorn/prefer-query-selector` rule

.eslintrc.cjs, dev/ts/component/download.ts, dev/ts/pages/elements-identification.ts, dev/ts/shared/main.ts
https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prefer-add-event-listener.md
Part of #2824
Covers #2742
=> chore(eslint): add `unicorn/prefer-add-event-listener` rule

.eslintrc.cjs, dev/ts/pages/bpmn-rendering.ts, dev/ts/pages/index.ts
To avoid to have to many changes by enabling `plugin:unicorn/recommended`, I choose to enable some rule one-by-one.
https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prefer-dom-node-text-content.md
Part of #2824 
Covers #2742
=> chore(eslint): add `unicorn/prefer-dom-node-text-content` rule

.eslintrc.cjs, test/config/jest-playwright.cjs, test/e2e/diagram.navigation.fit.test.ts, test/integration/matchers/toBeCell/index.ts, test/integration/matchers/toBeEdge/index.ts, test/integration/matchers/toBeShape/index.ts, test/unit/helpers/JsonBuilder.ts
https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prefer-logical-operator-over-ternary.md
Part of #2824
⚠️ For the code coverage, it was already the case before this PR.
Covers #2742
=> chore(eslint): add `unicorn/prefer-logical-operator-over-ternary` rule

.eslintrc.cjs, src/component/mxgraph/config/MarkerConfigurator.ts, src/component/parser/json/converter/ProcessConverter.ts, test/e2e/overlays.rendering.test.ts, test/unit/component/mxgraph/shape/render/BpmnCanvas.test.ts, test/unit/component/parser/json/BpmnJsonParser.group.test.ts, test/unit/component/parser/json/BpmnJsonParser.messageFlow.test.ts
https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/consistent-function-scoping.md
Part of #2824 
Covers #2742
=> chore(eslint): add `unicorn/consistent-function-scoping` rule

CONTRIBUTING.md
These changes clarify which issues accept contributions and how contributors should interact with core developers.
Closes #2810
- wording reviewed with Deepl
- the proposition described in the issue is not fully implemented as it could lead to the creation of PRs on undesirable subjects, which would then have to be closed. It has been replaced by something clearer (always talk to us, even if an issue is not marked as "PR approved" for now)
> that for other PRs, our responsiveness will be significantly reduced based on complexity and priority.
=> docs: clarify how contributions are accepted

.eslintrc.cjs, dev/ts/shared/main.ts, scripts/utils/parseBpmn.ts, src/component/helpers/array-utils.ts, src/component/mxgraph/BpmnCellRenderer.ts, src/component/mxgraph/BpmnGraph.ts, src/component/mxgraph/config/ShapeConfigurator.ts, src/component/mxgraph/renderer/style-utils.ts, src/component/mxgraph/style/style-updater.ts, src/component/parser/json/converter/ProcessConverter.ts, test/config/jest.image.ts, test/unit/component/mxgraph/renderer/StyleComputer.test.ts, test/unit/helpers/bpmn-model-expect.ts
https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/no-negated-condition.md
Part of #2824 
:warning:  For the code coverage, it was already the case before this PR.
Covers #2742
=> chore(eslint): add `unicorn/no-negated-condition` rule

.eslintrc.cjs, dev/ts/component/ThemedBpmnVisualization.ts, dev/ts/pages/elements-identification.ts, src/component/mxgraph/BpmnGraph.ts, src/component/mxgraph/renderer/style-utils.ts, src/component/mxgraph/shape/activity-shapes.ts, src/component/mxgraph/style/utils.ts, src/component/parser/json/converter/ProcessConverter.ts, test/e2e/helpers/visu/image-snapshot-config.ts, test/unit/helpers/JsonBuilder.ts
https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/no-useless-switch-case.md  
https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prefer-switch.md  
https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/switch-case-braces.md
Part of #2824 
Covers #2742
=> chore(eslint): add unicorn Switch rules

.github/pull_request_template.md
The new template is aligned with the content of the recently updated contribution guide. The aim is to ensure that we do not receive Pull Requests on non-priority topics and that the contribution respects our guidelines.
In particular, the template now includes a checklist that allows contributors to validate that they are following the contribution process.
closes #2872
- the template is inspired from the typescript-eslint PR template
- wording reviewed with Deepl
=> docs: clarify the Pull Request template

.github/pull_request_template.md
For external contributors, also clarify that the link to an existing issue is mandatory.
Covers #2872
=> docs: simplify PR template for core contributors

test/unit/helpers/JsonBuilder.test.ts, test/unit/helpers/JsonBuilder.ts
To avoid confusion, if the property `eventDefinitionOn` is set to `NONE` and the property `eventDefinitionKind` is set in the same instance of `BuildEventParameter`, an error is thrown.
=> test(JsonBuilder): not possible to have NONE `eventDefinitionOn` and `eventDefinitionKind` in same time in `BuildEventParameter`

test/unit/component/parser/json/BpmnJsonParser.event.with.event.definition.test.ts, test/unit/helpers/JsonBuilder.ts
Avoid duplication to add `EventDefinition` in the `Definitions` or in the `Event` objects:
- remove `addEventDefinitionsOnEvent` and `addEventDefinitionsOnDefinition`. The code was very similar.
- add `addEventDefinitions`
=> test(JsonBuilder): avoid duplicated code when adding `EventDefinition`

test/unit/helpers/JsonBuilder.test.ts, test/unit/helpers/JsonBuilder.ts
Currently, the id of the event definition generated by the `JsonBuilder` is not unique, but based on the BPMN Specification, it must be.
=> test(JsonBuilder): have unique id for event definition

test/unit/component/parser/json/BpmnJsonParser.callActivity.test.ts, test/unit/component/parser/json/BpmnJsonParser.event.none.test.ts, test/unit/component/parser/json/BpmnJsonParser.event.with.event.definition.test.ts, test/unit/component/parser/json/BpmnJsonParser.messageFlow.test.ts, test/unit/helpers/JsonBuilder.test.ts, test/unit/helpers/JsonBuilder.ts, test/unit/helpers/TestUtils.BpmnJsonParser.event.ts
Update the test helper `JsonBuilder` to set the properties:
- `source`: for Link event definition of Intermediate Catch Event
- `target`: for Link event definition of Intermediate Throw Event
And rename some existing types.
Covers #2906
=> test(JsonBuilder): add new properties for link events

test/unit/helpers/JsonBuilder.test.ts, test/unit/helpers/JsonBuilder.ts
For the unit tests for the link events, we need to have id for eventDefinition understandable and to have tests more readable.  
```json
"intermediateThrowEvent": {
"id": "source_id",
"linkEventDefinition": {
"id": "link_source_id",
"target": "link_target_id"
}
}
```
=> test(JsonBuilder): use the id of event for the id of eventDefinition

.eslintrc.cjs, scripts/utils/parseBpmn.ts, src/component/mxgraph/BpmnCellRenderer.ts, src/component/mxgraph/BpmnGraph.ts, src/component/mxgraph/config/ShapeConfigurator.ts, src/component/mxgraph/overlay/custom-overlay.ts, src/component/mxgraph/renderer/CoordinatesTranslator.ts, src/component/registry/bpmn-elements-registry.ts, test/shared/file-helper.ts
Add \`unicorn/prefer-at\`, \`unicorn/prefer-dom-node-dataset\`, \`unicorn/text-encoding-identifier-case\` rules.
https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/text-encoding-identifier-case.md  
https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prefer-dom-node-dataset.md  
https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prefer-at.md
Covers #2742
=> chore(eslint): enable 3 rules of the unicorn plugin

.eslintrc.cjs, dev/ts/component/ThemedBpmnVisualization.ts, scripts/utils/parseBpmn.ts, src/component/parser/json/converter/DiagramConverter.ts
https://eslint.org/docs/latest/rules/dot-notation
Part of https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/src/configs/stylistic-type-checked.ts
As there is to many changes and errors to fix with `stylistic-type-checked` eslint rules, we don't want to implement it.
But the `@typescript-eslint/dot-notation` rule allows the simplification of the code and the reading.
Covers #2742
=> chore(eslint): add `@typescript-eslint/dot-notation` rule

test/integration/matchers/matcher-utils.ts
During this POC #2812, I find a better way to write `toBpmnStyle()` to be more readable.
=> test: simplify the code of `toBpmnStyle()`

.eslintrc.cjs, test/config/jest.image.ts, test/performance/bpmn.load.performance.test.ts, test/performance/bpmn.navigation.performance.test.ts
https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prefer-string-slice.md
Covers #2742
=> chore(eslint): add `unicorn/prefer-string-slice` rule

src/component/registry/bpmn-elements-registry.ts, test/fixtures/bpmn/registry/1-pool-3-lanes-message-start-end-intermediate-events.bpmn, test/integration/dom.bpmn.elements.test.ts, test/integration/helpers/semantic-with-svg-utils.ts, test/integration/model.elements.api.test.ts, test/shared/model/bpmn-semantic-utils.ts
Filter duplicates generated when passing duplicated ids or kinds.
Closes #2921
=> fix: do not return duplicates in `BpmnElementsRegistry` "get model" APIs

src/component/parser/json/converter/EventDefinitionConverter.ts, src/component/parser/json/converter/ProcessConverter.ts, src/component/parser/json/converter/utils.ts, src/model/bpmn/json/baseElement/rootElement/eventDefinition.ts
Before, we only internally stored the `id`, `kind` and the number of occurrences of a `kind`.
For the link events, we need more data, like `source` and `target`.
Covers #2855
=> refactor: internally store more data of event definitions

.eslintrc.cjs, dev/ts/component/SvgExporter.ts, dev/ts/shared/main.ts, src/component/mxgraph/config/ShapeConfigurator.ts, src/component/registry/bpmn-model-registry.ts, src/model/bpmn/internal/shape/utils.ts, test/config/jest.image.ts, test/shared/visu/bpmn-page-utils.ts
https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prefer-set-has.md
https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prefer-set-size.md
https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prefer-number-properties.md
https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prefer-blob-reading-methods.md
https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prefer-code-point.md
Covers #2742
=> chore(eslint): add some unicorn rules

.eslintrc.cjs, dev/ts/shared/internal-helpers.ts, src/model/bpmn/internal/shape/utils.ts, test/config/ts-jest.cjs
I disabled:
*   the `unicorn/prefer-keyboard-event-key`; because `key` doesn't exist in the used ES version,
*   the `unicorn/prefer-module`; because we don't want to change a working configuration,
*   the `unicorn/prefer-string-replace-all` rule; because the `replaceAll` function is missing in the ES version used,
*   the `unicorn/no-new-array` rule, because it conflicts with `unicorn/new-for-builtins` (``Use `new Array()` instead of `Array()` `` ),
*   the `unicorn/no-null` rule; because we don't know the impact on `mxGraph` code,
*   the `unicorn/no-useless-undefined` rule, because the "undefined" value is useful where we use it and change some mxGraph code.
:information\_source: See all the rules https://github.com/sindresorhus/eslint-plugin-unicorn/#rules
Covers #2742
=> chore(eslint): use `unicorn/recommended` rules

.github/release-drafter.yml
Improve the  `release-drafter` template to better highlight
- breaking changes
- deprecation
- external contributions
=> docs(release-notes): improve template of the "highlight" paragraph

src/component/options.ts, src/component/parser/BpmnParser.ts, src/component/parser/parsing-messages.ts, test/unit/component/parser/parsing-messages.test.ts
Add a new option to prevent `ParserMessageCollector` from displaying warnings in the browser console.
closes #2698
=> feat: allow to disable parser console logs

src/component/mxgraph/GraphConfigurator.ts
Use a clearer name and use a more generic function.
=> refactor: improve the management of the panning cursor

src/component/parser/json/converter/ProcessConverter.ts, test/fixtures/bpmn/model-invalid-event-def-ref.bpmn, test/integration/model.elements.api.test.ts
Previously, the parser assumed that the identifier reference in the event definition was valid, i.e. that the identifier was defined at the top level.
If this was not the case, the corresponding event definition was not retrieved. The following code attempted to access properties with undefined values.
This generated an error.
- to reproduce the problem and check the fix in demo, you can use the diagram used in the new integration test introduced in this PR.
- this PR only adds an integration test and not a parsing unit test. If you think a unit test is required, please let me know.
=> fix: ignore invalid event definition reference

docs/contributors/maintainers.md
Use the new GitHub workflow that automatically create the GitHub release.
Closes https://github.com/process-analytics/bpmn-visualization-examples/issues/375
This PR requires that the workflow is available in the examples repository. See https://github.com/process-analytics/bpmn-visualization-examples/pull/584
[UPDATE 2024-01-09] The dependent PR has been merged.
=> docs: simplify the release in the examples repository

test/unit/component/parser/BpmnParser.test.ts
Add a test to check this use case.
This completes the textual content check.
=> test: check parsing of empty content

src/component/parser/xml/BpmnXmlParser.ts, test/fixtures/bpmn/xml-parsing/itp-commerce_Vizi-Modeler-for-Microsoft-Visio_7.7151.18707_bug-2857.bpmn, test/fixtures/bpmn/xml-parsing/special/simple-start-task-end_large_numbers_and_large_decimals.bpmn, test/integration/mxGraph.model.bpmn.elements.test.ts, test/unit/component/parser/xml/BpmnXmlParser.00.special.parsing.cases.test.ts, test/unit/component/parser/xml/BpmnXmlParser.itp-commerce.7-7151-18707.test.ts
The XML parser now ensures that the following elements have numeric attributes
- bounds of shapes
- label bounds of shapes and edges
- waypoints of edges
Previously, when the attribute contained too many decimals, the value was converted to a string instead of a number. Existing tests exhibited this behavior; they have been modified and enriched to cover all use cases and show that the issue is now fixed.
A high-level parsing test has also been added to use the diagram that was provided by the community to show the past problem.
closes #2857
Using the diagram provided to exhibit the issue in #2857 
https://github.com/process-analytics/bpmn-visualization-js/assets/27200110/d9cc22c3-73aa-4e30-bdb5-9971fbe3de45
=> fix: ensure numeric attributes are parsed as number

src/component/mxgraph/overlay/converter.ts, src/component/mxgraph/renderer/StyleComputer.ts, src/component/mxgraph/shape/event-shapes.ts, src/component/mxgraph/shape/render/icon-painter.ts, src/component/parser/json/converter/DiagramConverter.ts
Replace pure private static methods (i.e. method not using static property) by functions to better encapsulate the implementation logic.
These methods are generated as public in the JavaScript code, which is not necessary.
=> refactor: use internal functions rather than static private methods

src/component/mxgraph/config/ShapeConfigurator.ts
The private method that registered the shapes was a pure function, so it had been extracted from the ShapeConfigurator class.
The registration code has also been simplified to better reflect a configuration pattern (less explicit calls to the mxGraph registration code).
Part of initiative including #3041, #3042 and #3043 (more to come).
=> refactor: simplify shapes registration

src/component/mxgraph/config/ShapeConfigurator.ts, src/component/mxgraph/shape/utils.ts, test/integration/dom.container.div.test.ts, test/integration/helpers/html-utils.ts
Previously, this was done by modifying the `mxSvgCanvas2D` prototype. The new implementation limits side effects on applications that use `mxGraph` directly, and doesn't modify code the lib doesn't own.
The `mxGraph` implementation overriding is required to ensure that the label pointer-events is set to 'none'. New integration tests have been added to validate the old behavior and ensure that the refactoring has preserved it. In particular, more tests check the labels of a greater number of BPMN element types, and the value of the "pointer-events" property of labels is explicitly checked.
The overriding implementation has been simplified to reduce the copy/paste of `mxGraph` code. Instead, it now calls the standard `mxGraph` implementation with specific settings.
Continue the work started …
=> refactor: directly override `svgCanvas2D.getTextCss`

src/component/mxgraph/config/StyleConfigurator.ts, src/component/mxgraph/shape/activity-shapes.ts
Replace pure private methods (i.e. method not using class instance property) by functions to better encapsulate the implementation logic.
Do the same for private properties that can be replaced by constants. Such private methods and properties were generated as public in the JavaScript code, which was not necessary.
Continue the work started in #3041.
=> refactor: use internals instead of private class elements

src/component/mxgraph/shape/utils.ts
This reduces the maintenance (in particular if we want to migrate to maxGraph) and reduces the size of the bundle a bit.
The modified code is fully covered by integration tests.
This change will also increase the code coverage as some parts of the duplicated mxGraph code includes paths not used by `bpmn-visualization`.
This PR continues the work started in #3043 and #3046
=> refactor: reduce code duplicated from mxGraph to override shape canvas

src/component/mxgraph/GraphConfigurator.ts
Remove the container property as it is not used (it was defined in the constructor)
Panning cursor: remove extra condition as the graph is always enabled
=> refactor: simplify `GraphConfigurator`

src/component/mxgraph/BpmnRenderer.ts, src/component/mxgraph/renderer/CoordinatesTranslator.ts, src/component/mxgraph/shape/render/icon-painter.ts
`CoordinatesTranslator`: remove extra null check
`buildParameter`: shape properties are assumed to be set by the CellRender, according to the cell style. So only use properties for the shape style.
NOTE: we have a large number of tests, very varied, so they would have detected regressions in code changes if there were any.
=> refactor: simplify some code using the mxGraph API

.github/workflows/notify-new-version-available-on-npm.yml, .github/workflows/publish-npm.yml
The event send by the "npm publish" workflow was incorrect, it didn't correctly integrate the configuration tested in the playground repository.
The workflow notifying the R package included 2 issues
- the internal action wasn't checkout
- the name of the target repository contained a typo
The problems above have impacted the release of version `0.44.0`.
Running the fixed workflow manually fixed the problems for this particular release.
#3156 didn't provide a complete solution.
Problems detected during the 0.44.0 release:
- notif R package: no access to the internal action https://github.com/process-analytics/bpmn-visualization-js/actions/runs/10628821965/job/29464398491 
- build demo: version is not correctly resolved, it is empty so the checkout of the tag failed. …
=> ci: fix notification workflows used during releases

.github/actions/free-runner-disk-space-ubuntu/action.yml, .github/actions/log-disk-space/action.yml, .github/workflows/test-e2e.yml
The error had been occurring for a few weeks when running e2e tests for Chrome on Ubuntu.
Remove some cached tools to free up space as suggested in the official "runner-images" repository.
They have been some related issues reported since the end of August:
- 2024-08-30 https://github.com/actions/runner-images/issues/10511 on macOS. New version of XCode and related simulators were added to the images, so there is less space available
- 2024-09-29 https://github.com/actions/runner-images/issues/10699 on Ubuntu 24 which is very closed to the error we got [logs_29267977676.zip](https://github.com/user-attachments/files/17270168/logs_29267977676.zip)
=> ci: add workaround to prevent "no space left on device" error

.eslintrc.cjs, dev/ts/component/DropFileUserInterface.ts, dev/ts/component/SvgExporter.ts, src/component/mxgraph/BpmnCellRenderer.ts, src/component/mxgraph/config/StyleConfigurator.ts, src/component/mxgraph/shape/activity-shapes.ts, src/component/mxgraph/shape/event-shapes.ts, src/component/mxgraph/shape/render/BpmnCanvas.ts, src/component/mxgraph/style/style-updater.ts, src/component/parser/json/converter/CategoryConverter.ts, src/component/parser/json/converter/CollaborationConverter.ts, src/component/parser/json/converter/DiagramConverter.ts, src/component/parser/json/converter/EventDefinitionConverter.ts, src/component/parser/json/converter/GlobalTaskConverter.ts, src/component/parser/json/converter/ProcessConverter.ts, src/component/parser/json/converter/utils.ts, src/component/parser/parsing-messages.ts, src/component/parser/xml/BpmnXmlParser.ts, src/component/registry/bpmn-elements-registry.ts, src/component/registry/bpmn-model-registry.ts, src/component/registry/css-registry.ts, test/integration/helpers/html-utils.ts, test/shared/visu/bpmn-page-utils.ts
Make the members readonly when they are not reassigned outside the constructor. This improves type safety and promotes immutability.
This has been detected by SonarCloud. Use the related typescript-eslint rule to prevent this from appearing again.
The eslint errors are auto-fixable, so this change will be transparent for developers.
See https://typescript-eslint.io/rules/prefer-readonly/
=> refactor: make class members readonly when possible

.github/workflows/build.yml
The former sonar action was deprecated.
Use this new action which is a drop-replacement.
=> ci(build): switch to sonarqube-scan-action

CONTRIBUTING.md, docs/contributors/pull-request.md
Use the same convention as in other repositories of the Process Analytics project.
=> docs: update the branch naming convention in the Contributing Guidelines

docs/README.md, docs/contributors/README.md, docs/contributors/demo-page-css.md, docs/contributors/development.md, docs/contributors/documentation-guidelines.md
Add information about GitHub Actions and the addons repository
Highlight the architecture and documentation guidelines
Fix some typos and links
=> docs: add information for contributors

.github/workflows/publish-npm.yml
The client-payload was invalid, the property name and value must be enclosed in double quotes.
Fixes #3275 
Inspiration: https://github.com/bonitasoft/bonita-doc/blob/43c8063dc7dae0a976ed95b23f0ce59872215675/.github/workflows/push-content.yml
=> ci: fix "client-payload" in the event sent after npm publish

.github/dependabot.yml
The configuration must be switched to flat configuration prior migrating to eslint v9.
=> chore(dependabot): ignore some eslint dependencies

.github/dependabot.yml, package-lock.json, package.json, src/bpmn-visualization.ts, src/component/parser/json/converter/ProcessConverter.ts
Update configuration and code to ensure compatibility with the new TypeScript version.
- Use a recent version of `@types/node` that matches the Node.js version used for building the project.  
The previous version had type issues related to `AbortSignal`, similar to the upgrade to TypeScript 4.9 (see 6356b3e).
- Add an attribute to retain the triple-slash reference to `mxGraph` types in the type definitions included in the npm package.  
As of TypeScript 5.5, this is required; otherwise, the reference is omitted.
This work started in #3124 in August 2024. At that time, we haven't found in the TypeScript documentation the behavior change about triple slash references.
=> chore(deps-dev): bump typescript from 5.4.5 to 5.8.2

src/component/mxgraph/BpmnCellRenderer.ts, src/component/mxgraph/BpmnGraph.ts, src/component/mxgraph/GraphConfigurator.ts, src/component/mxgraph/overlay/converter.ts, src/component/mxgraph/overlay/custom-overlay.ts, src/component/mxgraph/overlay/shapes.ts, src/component/mxgraph/overlay/updater.ts, src/component/mxgraph/renderer/CoordinatesTranslator.ts, src/component/mxgraph/renderer/style-utils.ts, src/component/mxgraph/shape/utils.ts, src/component/mxgraph/style/style-updater.ts, test/integration/matchers/matcher-utils.ts, test/unit/component/mxgraph/overlay/converter.test.ts
There is no need to prefix our own elements by "mx" when we extend the mxGraph code.
This makes the code easier to read, and eventually, prepare the switch to maxGraph.
These changes only apply to bpmn-visualization internals, there is no impact for end users.
=> refactor: remove reference to "mx" in classes, types and JSDoc
