README.md

* Product Management said no need to talk about the fact that this is based on a library. We communicate about the solution that could be made of several libraries in the end.

fix(readme): Update definition of the project

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/other.md
.github/ISSUE_TEMPLATE/question.md

[infra] add issue templates

---

CODE_OF_CONDUCT.md
README.md

[infra] add code of conduct v2.0

---

CONTRIBUTING.md
README.md

[infra] add how to contribute

---

.github/pull_request_template.md

[infra] add pull request template

---

.eslintrc.js
.github/workflows/build.yml
.prettierrc.js
package-lock.json
package.json
src/bpmn-visu-js/greet.ts
src/bpmn-visu-js/main.ts
src/index.ts

Basic setup: linting

---

package-lock.json
package.json
rollup.config.js
src/bpmn-visu-js/main.ts
src/bpmn-visu-js/mx-graph-visu.ts

[Infra] mxGraph library added

---

README.md
package.json

Also update readme with nodejs requirements

[infra] package.json: update name and version + add description

---

.github/workflows/build.yml
.gitignore
.nycrc
package-lock.json
package.json
src/component/parser/json/BpmnJsonParser.ts
src/component/parser/json/Definitions.ts
src/component/parser/json/converter/AbstractConverter.ts
src/component/parser/json/converter/ShapeConverter.ts
src/component/parser/json/converter/ShapeModelConverter.ts
src/component/parser/xml/BpmnXmlParser.ts
src/model/bpmn/shape/Shape.ts
src/model/bpmn/shape/ShapeBpmnElement.ts
src/model/bpmn/shape/ShapeBpmnElementKind.ts
test/component/parser/json/BpmnJsonParser.test.ts
test/component/parser/xml/BpmnXmlParser.test.ts
tsconfig.json

Parse one/several start events from one/several processes.
Covers #22

[FEAT] Parse start events from XML content

---

CONTRIBUTING.md
README.md

Explain the different command to install environment & run the tests
Covers #22 
Depends on #31

[Doc] Update contributing guide to test

---

CONTRIBUTING.md

Add advices in contributing guide

---

src/component/parser/xml/BpmnXmlParser.ts
src/model/bpmn/Bounds.ts
src/model/bpmn/shape/Shape.ts
test/component/parser/json/BpmnJsonParser.test.ts
test/component/parser/xml/BpmnXmlParser.test.ts

Parse BPMN Bounds

---

src/component/mxgraph/MxGraphConfigurator.ts
src/component/parser/json/converter/AbstractConverter.ts
src/component/parser/json/converter/ShapeConverter.ts
src/component/parser/json/converter/ShapeModelConverter.ts
src/model/bpmn/shape/ShapeBpmnElementKind.ts
test/component/parser/json/BpmnJsonParser.test.ts
test/component/parser/xml/BpmnXmlParser.test.ts

[FEAT] Display user task

---

.github/workflows/build.yml
package.json

[INFRA] Fix lint & lint-check command on MacOs

---

src/component/graph/Graph.ts
src/component/mxgraph/MxGraphConverter.ts
src/component/parser/json/BpmnJsonParser.ts
src/component/parser/json/Definitions.ts
src/component/parser/json/converter/EdgeConverter.ts
src/component/parser/json/converter/EdgeModelConverter.ts
src/model/bpmn/edge/Edge.ts
src/model/bpmn/edge/SequenceFlow.ts
test/component/parser/json/BpmnJsonParser.test.ts
test/component/parser/xml/BpmnXmlParser.test.ts

[FEAT] introduce support of sequence flows

---

.nycrc.json
package-lock.json
package.json

[INFRA] Update the configuration of the coverage

---

src/component/graph/Graph.ts

Disable the MxGraph's features to edit the Cells & the Edge labels
Closes #41

[FEAT] Lock cells & edge labels

---

test/component/parser/json/BpmnJsonParser.test.ts

Add tests for parsing of user task & start event without name
Closes #56

[FEAT] Possible to display Start event & User Task without name

---

.github/workflows/build.yml
README.md

Describe the current release procedure.
It has been followed to create [0.1.0](https://github.com/bonitasoft-labs/bpmn-visu-js/releases/tag/v0.1.0)

[DOC] manual release procedure

---

src/component/graph/Graph.ts
src/component/mxgraph/MxGraphConverter.ts
src/component/mxgraph/MxGraphRenderer.ts
src/component/parser/BpmnParser.ts
src/model/bpmn/BpmnModel.ts
test/component/parser/BpmnParser.test.ts
test/component/parser/json/BpmnJsonParser.test.ts

hide internal logic to client code
- bpmn source parsing: introduce a high level parser and a BpmnModel class
- mxgraph rendering: the mxgraph renderer is managing the mxgraph transaction

Refactor: introduce high level parsing and rendering

---

README.md

[DOC] describe how to see a demo of the project

---

src/component/mxgraph/MxGraphConfigurator.ts
src/model/bpmn/shape/ShapeBpmnElementKind.ts
test/component/parser/json/BpmnJsonParser.parallelGateway.test.ts
test/component/parser/xml/BpmnXmlParser.parallelGateway.test.ts

[FEAT] Display Parallel gateway

---

src/component/graph/Graph.ts
src/component/mxgraph/MxGraphConfigurator.ts
src/component/mxgraph/MxGraphRenderer.ts
src/service/MxGraphFactoryService.ts

[INFRA] Refactored usage of mxGraphFactory

---

src/component/mxgraph/MxGraphConfigurator.ts
src/model/bpmn/shape/ShapeBpmnElementKind.ts
test/unit/component/parser/json/BpmnJsonParser.task.test.ts
test/unit/component/parser/xml/BpmnXmlParser.task.test.ts

[FEAT] Display task

---

README.md

The link was missing, we displayed only the badge

[DOC] fix releases link in README

---

src/component/mxgraph/MxGraphRenderer.ts
src/component/parser/json/converter/DiagramConverter.ts
src/component/parser/json/converter/ProcessConverter.ts
src/model/bpmn/edge/Edge.ts
src/model/bpmn/edge/Waypoint.ts
test/unit/component/parser/json/BpmnJsonParser.sequenceFlow.test.ts
test/unit/component/parser/json/JsonTestUtils.ts
test/unit/component/parser/xml/BpmnXmlParser.sequenceFlow.test.ts

Display Waypoints of SequenceFlow with relative coordinates
Closes #82

[FEAT] Display Waypoints of SequenceFlow

---

src/component/mxgraph/MxGraphConfigurator.ts
src/component/mxgraph/ShapeConfigurator.ts
src/component/mxgraph/StyleConfigurator.ts
src/component/mxgraph/shape/EndEventShape.ts
src/service/MxGraphFactoryService.ts
test/e2e/View.test.ts

[FEAT] Render end event

---

README.md
src/component/mxgraph/ShapeConfigurator.ts
src/component/mxgraph/StyleConfigurator.ts
src/component/mxgraph/shape/EndEventShape.ts
src/component/mxgraph/shape/StartEventShape.ts
test/e2e/View.test.ts

[FEAT] Render Start event

---

package-lock.json
package.json
rollup.config.js
src/component/parser/xml/BpmnXmlParser.ts
test/unit/component/parser/xml/BpmnXmlParser.exclusiveGateway.test.ts
test/unit/component/parser/xml/BpmnXmlParser.parallelGateway.test.ts
test/unit/component/parser/xml/BpmnXmlParser.process.test.ts
test/unit/component/parser/xml/XMLTestUtils.ts

Use the 'entities' lib in the 'fast-xml-parser ' configuration to perform
attribute decoding.
Closes #132

[FEAT] decode xml entities in bpmn input source

---

README.md
docs/architecture/bpmn-parsing.adoc
docs/bpmn-support-how-to.adoc

[DOC] BPMN xml parsing

---

src/component/parser/json/EventDefinition.ts
src/component/parser/json/EventDefinitions.ts
src/component/parser/json/converter/ProcessConverter.ts
test/unit/component/parser/json/BpmnJsonParser.startEvent.test.ts

[FEAT] display only None Start Event

---

src/component/parser/json/converter/ProcessConverter.ts
test/unit/component/parser/json/BpmnJsonParser.event.end.none.test.ts

[FEAT] display only None End Event

---

package.json
src/component/ui_ux/DropFileUserInterface.ts
src/config/main.ts
src/index.html
src/static/css/main.css

Drag & Drop interface
Closes #25

[FEAT] Drag & Drop BPMN file

---

package-lock.json
package.json

[INFRA] bump 'minimist' dev dependency

---

package.json

[INFRA] update ts-mxgraph dependency url

---

CONTRIBUTING.md
README.md
docs/bpmn-support-roadmap.adoc
package.json
src/index.html
test/e2e/View.test.ts

[DOC] update links after repository move and renaming

---

docs/bpmn-support-roadmap.adoc
docs/bpmn-support.adoc

Also provide info about the rendering status

[DOC] list supported BPMN elements

---

.eslintrc.js
src/component/parser/json/converter/AbstractConverter.ts
src/component/parser/json/converter/CollaborationConverter.ts
src/component/parser/json/converter/DiagramConverter.ts
src/component/parser/json/converter/ProcessConverter.ts
src/component/ui_ux/DropFileUserInterface.ts

[INFRA] Prohibit to log with console.xxx (except console.error)

---

docs/bpmn-support-roadmap.adoc
docs/bpmn-support.adoc
src/component/mxgraph/shape/event-shapes.ts
src/component/parser/json/converter/ProcessConverter.ts
src/model/bpmn/shape/ShapeBpmnEventKind.ts
test/e2e/View.test.ts
test/unit/component/parser/json/BpmnJsonParser.event.start.timer.test.ts

**Note**
- this PR contains several refactoring commits that are motivated by the new `timer start event` support
Closes #71

[FEAT] display timer start event

---

docs/bpmn-support-roadmap.adoc
docs/bpmn-support.adoc
src/model/bpmn/shape/ShapeBpmnElementKind.ts
src/model/bpmn/shape/ShapeBpmnEventKind.ts
test/unit/component/parser/json/BpmnJsonParser.event.end.none.test.ts
test/unit/component/parser/json/BpmnJsonParser.event.intermediate.throw.none.test.ts

[FEAT] Display Throw None Intermediate Event

---

docs/bpmn-support.adoc
src/component/mxgraph/ShapeConfigurator.ts
src/component/mxgraph/StyleConfigurator.ts
src/component/mxgraph/shape/event-shapes.ts
test/e2e/View.test.ts

[FEAT] Render Throw None Intermediate Event

---

docs/bpmn-support.adoc
src/component/mxgraph/shape/event-shapes.ts
src/model/bpmn/shape/ShapeBpmnEventKind.ts
test/unit/component/parser/json/BpmnJsonParser.event.intermediate.throw.message.test.ts

[FEAT] Display Throw Message Intermediate Event

---

docs/bpmn-support.adoc
test/unit/component/parser/json/BpmnJsonParser.event.intermediate.catch.message.test.ts

[FEAT] Display Catch Message Intermediate Event

---

docs/bpmn-support.adoc
src/component/mxgraph/shape/event-shapes.ts
test/unit/component/parser/json/BpmnJsonParser.event.start.message.test.ts

[FEAT] Display Message Start Event

---

docs/bpmn-support.adoc
src/component/mxgraph/shape/event-shapes.ts
test/unit/component/parser/json/BpmnJsonParser.event.end.message.test.ts

[FEAT] Display Message End Event

---

docs/bpmn-support.adoc
src/component/mxgraph/shape/event-shapes.ts
test/e2e/View.test.ts

[FEAT] Render Throw Message Intermediate Event

---

docs/bpmn-support.adoc
src/component/mxgraph/shape/event-shapes.ts
test/e2e/View.test.ts

[FEAT] Render Message Start Event

---

README.md
docs/bpmn-support.adoc
src/component/mxgraph/shape/event-shapes.ts

- Timer Start Event: closes #243
- Catch Timer Intermediate Event: closes #217

[FEAT] Render Timer Events

---

src/component/mxgraph/extension/MxScaleFactorCanvas.ts
src/component/mxgraph/shape/event-shapes.ts
src/component/mxgraph/shape/gateway-shapes.ts
src/component/mxgraph/shape/task-shapes.ts

Methods moved to util class:
* configureCanvasForIcon
* translateToStartingIconPosition
closes #261

[REFACTOR] avoid duplication of shape utility methods

---

docs/architecture/bpmn-support-how-to.adoc
docs/bpmn-support.adoc
src/component/mxgraph/StyleConfigurator.ts
src/model/bpmn/shape/ShapeBpmnElementKind.ts
src/model/bpmn/shape/ShapeUtil.ts
test/e2e/mxGraph.model.test.ts
test/unit/component/parser/json/BpmnJsonParser.call.activity.test.ts
test/unit/component/parser/json/BpmnJsonParser.sequenceFlow.conditional.test.ts
test/unit/component/parser/json/BpmnJsonParser.sequenceFlow.default.test.ts

Closes #77
**Render of the [B.1.0.bpmn file from BPMN-MIWG](https://github.com/bpmn-miwg/bpmn-miwg-test-suite/blob/master/Reference/B.1.0.bpmn)**

[FEAT] display call activity

---

docs/bpmn-support.adoc
src/component/mxgraph/MarkerConfigurator.ts
src/component/mxgraph/MxGraphConfigurator.ts
src/component/mxgraph/StyleConfigurator.ts
src/service/MxGraphFactoryService.ts
test/e2e/mxGraph.model.test.ts

[FEAT] Render Default Sequence flow

---

CONTRIBUTING.md
README.md
docs/intro.adoc

Update the documentation for both users and contributors.
closes #37

[DOC] add references to the demo environment

---

CONTRIBUTING.md

closes #187 
Sentence about "how to sign" is inspired from https://cla.opensource.microsoft.com/
```
When you contribute to a Microsoft open source project on GitHub with a new
pull request, a bot will evaluate whether you have signed the CLA. If required,
the bot will comment on the pull request, including a link to this system to accept
the agreement.
```

[DOC] explain how and why signing the CLA

---

docs/bpmn-support.adoc
src/component/mxgraph/StyleConfigurator.ts
src/component/parser/json/converter/ProcessConverter.ts
src/model/bpmn/edge/SequenceFlowKind.ts
src/model/bpmn/shape/ShapeUtil.ts
test/e2e/mxGraph.model.test.ts
test/unit/component/parser/json/BpmnJsonParser.sequenceFlow.conditional.test.ts

[FEAT] Render Conditional Sequence Flow

---

CONTRIBUTING.md

[DOC] fixed anchor in CONTRIBUTING

---

docs/bpmn-support.adoc
src/component/mxgraph/ShapeConfigurator.ts
src/component/mxgraph/shape/task-shapes.ts
src/component/parser/json/converter/ProcessConverter.ts
src/model/bpmn/shape/ShapeBpmnElement.ts
src/model/bpmn/shape/ShapeBpmnElementKind.ts
test/e2e/mxGraph.model.test.ts
test/unit/component/parser/json/BpmnJsonParser.sequenceFlow.conditional.test.ts
test/unit/component/parser/json/BpmnJsonParser.sequenceFlow.default.test.ts
test/unit/component/parser/json/BpmnJsonParser.task.receive.test.ts

[FEAT] Display Receive task

---

docs/bpmn-support.adoc

Issue introduced in 40b9acbd (merge issue)
I hope this will be easier to detect directly in PR when #180 will be implemented

[DOC] fix bpmn-support activities table issue

---

src/component/mxgraph/MxGraphRenderer.ts
src/component/mxgraph/StyleConfigurator.ts
src/component/parser/json/converter/DiagramConverter.ts
test/e2e/mxGraph.model.test.ts
test/unit/component/mxgraph/MxGraphRenderer.test.ts

Closes #278 
Render with & without font

[FEAT] Render the Label Font of a Edge

---

src/component/mxgraph/MxGraphRenderer.ts
src/component/mxgraph/StyleConfigurator.ts
src/component/mxgraph/StyleUtils.ts
src/component/mxgraph/extension/MxScaleFactorCanvas.ts
src/component/mxgraph/shape/IconPainter.ts
src/component/mxgraph/shape/event-shapes.ts
src/component/mxgraph/shape/gateway-shapes.ts
src/component/mxgraph/shape/task-shapes.ts

[REFACTOR] Introduce icons painter service

---

src/component/BpmnVisu.ts
src/component/mxgraph/MxGraphConfigurator.ts
src/component/mxgraph/MxGraphRenderer.ts
src/component/mxgraph/extension/CoordinatesTranslator.ts
test/unit/component/mxgraph/MxGraphRenderer.test.ts

Extract the computation code from MxGraphRenderer into a new class to better separate responsibilities.

[REFACTOR] simplify relative coordinates computation

---

src/component/mxgraph/MxGraphRenderer.ts
src/component/mxgraph/StyleConfigurator.ts
src/component/mxgraph/extension/CoordinatesTranslator.ts
test/unit/component/mxgraph/MxGraphRenderer.test.ts

**Render Edge Label**
Closes #280

[FEAT] Render Edge Label

---

test/unit/component/parser/json/BpmnJsonParser.event.boundary.non.interrupting.message.test.ts

[FEAT] Display Non-interrupting Message Intermediate Event Attached to an Activity Boundary

---

docs/bpmn-support.adoc
src/component/mxgraph/MxGraphRenderer.ts
src/component/mxgraph/StyleConfigurator.ts
src/component/mxgraph/shape/activity-shapes.ts
test/unit/component/mxgraph/MxGraphRenderer.test.ts

[FEAT] Render Expanded Embedded Sub-Process

---

src/component/BpmnVisualization.ts
src/demo/index.ts
test/e2e/mxGraph.dom.test.ts
test/e2e/mxGraph.model.test.ts

Match the library name for consistency.

[REFACTOR] rename BpmnVisualization main class

---

test/e2e/mxGraph.model.test.ts
test/fixtures/bpmn/model-badly-attached-elements.bpmn
test/fixtures/bpmn/model-complete-semantic.bpmn
test/fixtures/bpmn/model-coordinates-relative-to-pool.bpmn

[INFRA] sync file loader for model tests

---

docs/bpmn-support.adoc
test/e2e/mxGraph.model.test.ts
test/fixtures/bpmn/model-complete-semantic.bpmn

[FEAT] Detect end signal event

---

docs/bpmn-support.adoc
test/e2e/mxGraph.model.test.ts
test/fixtures/bpmn/model-complete-semantic.bpmn

[FEAT] Detect Catch Signal Intermediate Event

---

docs/bpmn-support.adoc
test/e2e/mxGraph.model.test.ts
test/fixtures/bpmn/model-complete-semantic.bpmn

[FEAT] Detect Throw Signal Intermediate Event

---

docs/bpmn-support.adoc
test/e2e/mxGraph.model.test.ts
test/fixtures/bpmn/model-complete-semantic.bpmn

[FEAT] Detect Non-interrupting Signal Intermediate Event Attached to an Activity Boundary

---

docs/architecture/images/architecture/internal-model.svg
docs/bpmn-support.adoc
src/component/mxgraph/config/StyleConfigurator.ts
src/component/parser/json/converter/DiagramConverter.ts
src/component/parser/json/converter/ProcessConverter.ts
src/model/bpmn/edge/AssociationDirectionKind.ts
src/model/bpmn/edge/Edge.ts
src/model/bpmn/edge/Flow.ts
src/model/bpmn/edge/FlowKind.ts
test/e2e/mxGraph.model.test.ts
test/fixtures/bpmn/model-complete-semantic.bpmn
test/unit/component/parser/json/BpmnJsonParser.association.test.ts

[FEAT] detect association

---

docs/bpmn-support.adoc
src/component/mxgraph/config/StyleConfigurator.ts
test/unit/component/mxgraph/config/StyleConfigurator.test.ts

[FEAT] Render Association

---

tsconfig.json

[INFRA] Activate TypeScript strict type checking options: strictBindCallApply

---

tsconfig.json

[INFRA] Activate `alwaysStrict` compiler option

---

docs/bpmn-support.adoc
src/component/mxgraph/shape/render/BpmnCanvas.ts
src/component/mxgraph/shape/render/IconPainter.ts

Closes #303 
Closes #449
Closes #453

[FEAT] Render the Activity Loop Marker

---

src/component/mxgraph/StyleUtils.ts
src/component/mxgraph/config/StyleConfigurator.ts
src/component/mxgraph/shape/activity-shapes.ts
test/e2e/mxGraph.model.test.ts
test/unit/component/mxgraph/config/StyleConfigurator.test.ts

Consider the expand icon as a marker (sub process). This simplifies the markers management and will help for positioning in the future (#466)

[REFACTOR] activity markers style mutualization

---

.github/dependabot.yml

Mainly for commit message prefix and reviewers

[INFRA] setup dependabot configuration

---

docs/bpmn-support.adoc
src/component/mxgraph/shape/event-shapes.ts
src/model/bpmn/shape/ShapeBpmnEventKind.ts
test/e2e/mxGraph.model.test.ts
test/fixtures/bpmn/model-complete-semantic.bpmn
test/unit/component/parser/json/BpmnJsonParser.event.test.ts

Closes #95 
Closes #97 
Event Definition on Top
Expected
Result
Event Definition on Event
Expected
Result

[FEAT] Detect Throw & Catch Link Intermediate Events

---

docs/bpmn-support.adoc
src/component/mxgraph/shape/event-shapes.ts
src/component/mxgraph/shape/render/BpmnCanvas.ts
src/component/mxgraph/shape/render/IconPainter.ts

[FEAT] Render Throw & Catch Link Intermediate Events

---

docs/bpmn-support.adoc
src/component/mxgraph/config/ShapeConfigurator.ts
src/component/mxgraph/shape/activity-shapes.ts
src/model/bpmn/shape/ShapeBpmnElementKind.ts
test/e2e/mxGraph.model.test.ts
test/fixtures/bpmn/model-complete-semantic.bpmn
test/unit/component/mxgraph/config/StyleConfigurator.test.ts
test/unit/component/parser/json/BpmnJsonParser.flowNode.test.ts
test/unit/component/parser/json/BpmnJsonParser.label.bounds.test.ts
test/unit/component/parser/json/BpmnJsonParser.label.font.test.ts
test/unit/component/parser/json/BpmnJsonParser.label.test.ts
test/unit/component/parser/json/BpmnJsonParser.marker.test.ts
test/unit/component/parser/json/BpmnJsonParser.sequenceFlow.conditional.test.ts
test/unit/component/parser/json/BpmnJsonParser.sequenceFlow.default.test.ts

[FEAT] Detect Send task

---

src/component/parser/json/converter/ProcessConverter.ts
src/component/parser/xml/bpmn-json-model/baseElement/flowNode/activity/activity.ts
test/fixtures/bpmn/xml-parsing/trisotech-bpmn-modeler-6.2.0_A.4.0-export.bpmn
test/unit/component/parser/json/BpmnJsonParser.event.test.ts
test/unit/component/parser/json/BpmnJsonParser.sub.process.test.ts
test/unit/component/parser/xml/BpmnXmlParser.trisotech-bpmn-modeler-6_2_0.test.ts

Closes #359 
Closes #192 
1st step to render subprocess elements.

 [FEAT] Detect Events on Non Event Sub-Process

---

package-lock.json
package.json

Changelog: https://github.com/NaturalIntelligence/fast-xml-parser/blob/master/docs/CHANGELOG.md

[INFRA] Bump fast-xml-parser from 3.16.0 to 3.17.4

---

CONTRIBUTING.md

update of CONTRIBUTING.md
add missing information for examples update after release

[DOC] update release steps

---

CONTRIBUTING.md
jest-puppeteer.config.js
rollup.config.js
test/e2e/bpmn.rendering.test.ts
test/e2e/mxGraph.view.test.ts

[INFRA] Use dedicated port for e2e and dev servers

---

src/static/js/demo.js
src/static/js/non-regression.js

[BUG] documentReady must take a function callback as parameter

---

CONTRIBUTING.md
docs/development/README.md

[DOC] improve guidelines for contributors

---

docs/development/README.md

This an attempt to order page by topic to let contributors find information
more easily.

[DOC] order the development home page

---

README.md

Won't never means "will not never" which does not make sense.
Won't ever could also be a possibility but it would make the statement a bit 'angry' (in my view).

[FIX] fix a small english mistake in the readme

---

.theia/settings.json

[INFRA] Add settings for gitpod

---

README.md

[DOC] add npm package badge

---

.github/pull_request_template.md
CONTRIBUTING.md
README.md
docs/development/pull-request.md

[DOC] rework icons in markdown

---

test/e2e/ExpectModelUtils.ts
test/e2e/mxGraph.model.test.ts

[TEST] Add expect model utils file

---

scripts/utils/parseBpmn.ts
src/component/BpmnVisualization.ts
src/component/parser/BpmnParser.ts
src/component/parser/json/BpmnJsonParser.ts
test/unit/component/parser/BpmnParser.test.ts
test/unit/component/parser/json/JsonTestUtils.ts

Clarify function names as they return a new instance.

[REFACTOR] rename parser creation functions

---

docs/development/bpmn-support-how-to.md

[DOC] Help debugging format errors of BPMN file in e2e tests

---

test/e2e/ExpectModelUtils.ts
test/e2e/matchers/index.ts
test/e2e/matchers/toBeShape/index.ts
test/e2e/mxGraph.model.test.ts

[TEST] Introduce 'toBeScriptTask' Jest extension

---

docs/development/maintainers.md

[DOC] Add info about npm publish

---

src/component/mxgraph/MxGraphConfigurator.ts

[FEAT] Change mouse cursor while panning

---

src/component/BpmnVisualization.ts
src/component/mxgraph/BpmnMxGraph.ts
src/component/mxgraph/MxGraphConfigurator.ts
src/component/mxgraph/MxGraphRenderer.ts
src/component/mxgraph/config/StyleConfigurator.ts
src/component/mxgraph/renderer/CoordinatesTranslator.ts

- Extract BpmnMxGraph class in separate file
- Replace all mxGraph type by BpmnMxGraph

[REFACTOR] Extract BpmnMxGraph class in separate file

---

docs/development/maintainers.md

Based on `0.6.0` release feedbacks

[DOC] improve the release process

---

docs/contributors/maintainers.md

until tweeting is automated I think it is convenient to have it here
check #787 for the automatic tweeting

[DOC] Template for release tweet in Release doc

---

.github/release-drafter.yml

Add guidance for a short introduction: the content of URL previews will better explain
what we have done in the release.
Currently, the preview displays "thanks to all contributors" and no news about the changes.

[INFRA] Improve release-drafter template

---

src/component/mxgraph/StyleUtils.ts
src/component/mxgraph/config/ShapeConfigurator.ts
src/component/registry/bpmn-elements-registry.ts
src/component/registry/css-registry.ts
src/demo/index.ts
src/elements-identification.html
src/static/js/elements-identification.js
test/e2e/helpers/visu/bpmn-puppeteer-utils.ts
test/e2e/helpers/visu/html-utils.ts
test/e2e/mxGraph.dom.test.ts
test/unit/component/registry/css-registry.test.ts

[FEAT] Add CSS classes to BPMN elements

---

src/component/helpers/array-utils.ts
src/component/parser/json/converter/CollaborationConverter.ts
src/component/parser/json/converter/DiagramConverter.ts
src/component/parser/json/converter/EventDefinitionConverter.ts
src/component/parser/json/converter/GlobalTaskConverter.ts
src/component/parser/json/converter/ProcessConverter.ts
src/component/parser/json/converter/utils.ts
src/component/registry/bpmn-elements-registry.ts
test/unit/component/parser/xml/BpmnXmlParser.trisotech-bpmn-modeler-6_2_0.test.ts

Move ensureIsArray() form parser utils to an array utils

[REFACTORING] Introduce an array utils

---

src/component/registry/bpmn-elements-registry.ts

Fix copy/paste typo in function names in TSDoc.

[DOC] Fix TSDoc in BpmnElementsRegistry

---

src/component/registry/bpmn-elements-registry.ts

we have this kind of example for the other 2 API methods so I think it is a good idea to have it here as well

[DOC] example tsdoc for addCssClasses method

---

src/component/helpers/array-utils.ts
src/component/registry/bpmn-elements-registry.ts
src/component/registry/css-registry.ts
src/demo/index.ts
src/elements-identification.html
src/static/js/elements-identification.js
test/e2e/helpers/visu/html-utils.ts
test/e2e/mxGraph.dom.test.ts
test/fixtures/bpmn/registry/1-pool-3-lanes-message-start-end-intermediate-events.bpmn
test/unit/component/registry/css-registry.test.ts

Provide an API close to the one that already exists to add CSS classes.
covers #942

[FEAT] Add new API to remove CSS classes from BPMN elements

---

src/component/registry/bpmn-elements-registry.ts
src/component/registry/css-registry.ts
test/e2e/helpers/visu/html-utils.ts
test/e2e/mxGraph.dom.test.ts
test/fixtures/bpmn/registry/1-pool-3-lanes-message-start-end-intermediate-events.bpmn
test/unit/component/registry/css-registry.test.ts

[FEAT] Add new API to toggle CSS classes for BPMN elements

---

test/performance/bpmn.load.performance.test.ts
test/performance/bpmn.navigation.performance.test.ts

Due to some changes, the path to data.js file was not proper and data was not saved after the test run

[INFRA] Fix bad path in perf tests

---

src/bpmn-visualization.ts

we need mxConstants for the examples with customization

[INFRA] export mxgraph.mxConstants

---

.github/workflows/generate-demo-preview.yml
.github/workflows/upload-demo-archive.yml

[INFRA] Publish demo preview for Pull Request

---

src/component/mxgraph/overlay/OverlayConverter.ts
src/component/registry/types.ts
test/unit/component/mxgraph/overlay/OverlayConverter.test.ts

Make 'center' and 'middle' positions available.

[FEAT] Add new overlay positions

---

src/component/mxgraph/config/ShapeConfigurator.ts

You explicit types instead of any when possible.

[REFACTOR] Update types in mxCellRenderer overlays management

---

package-lock.json
package.json
src/component/mxgraph/BpmnMxGraph.ts
src/component/mxgraph/config/ShapeConfigurator.ts
src/component/mxgraph/overlay/shapes.ts
tsconfig.typedoc.json

This let us remove some hack we introduced to fix some types. Some issues remain
and will be fixed in typed-mxgraph later.

[INFRA] dev - Bump typed-mxgraph from 1.0.0 to 1.0.1

---

README.md
docs/users/intro.adoc

Integrate feedback from @Lamicque

[DOC] Improve the bpmn-visualization presentation sentence

---

docs/users/overview.adoc

Integrate feedback from @Lamicque

[DOC] Improve the Diagram Navigation paragraph in user documentation

---

CONTRIBUTING.md

[DOC] Review Configuration vs Customization

---

src/component/mxgraph/BpmnMxGraph.ts
src/component/parser/json/converter/DiagramConverter.ts
src/component/parser/json/converter/ProcessConverter.ts

Some rules from the prettier library changed: #1289

[FIX] Fix lint after bump of prettier library

---

src/component/registry/types.ts

[DOC] Improve the Overlay API TSDoc

---

.github/release-drafter.yml

Add new categories that are more precise than 'BPMN diagram usability'.
relates to #1267

[INFRA] Add new release-drafter categories

---

docs/contributors/development.md

This prevents pre-commit hook error.

[DOC] Add settings for husky when using nvm

---

package-lock.json
package.json
src/component/mxgraph/shape/edges.ts

Also remove hacks due to types issues in the previous typed-mxgraph version.

[INFRA] dev - Bump typed-mxgraph from 1.0.2 to 1.0.3

---

src/component/mxgraph/shape/activity-shapes.ts
src/component/mxgraph/shape/event-shapes.ts
src/component/mxgraph/shape/flow-shapes.ts
src/component/mxgraph/shape/gateway-shapes.ts
src/component/mxgraph/shape/render/BpmnCanvas.ts
src/component/mxgraph/shape/render/IconPainter.ts
src/component/mxgraph/shape/render/render-types.ts
test/unit/component/mxgraph/shape/render/BpmnCanvas.test.ts

[REFACTOR] Improve naming consistency in painting code

---

.github/workflows/generate-demo-preview.yml
dev/index.html

Fix the value of the attribute.

[EXAMPLE] Fix selected attribute in the demo page

---

docs/contributors/development.md

Provide the command to install the right version.

[DOC] Ensure contributors use npm@6

---

test/integration/config/mxgraph-config.ts
test/integration/dom.bpmn.elements.test.ts
test/integration/dom.container.div.test.ts
test/integration/dom.css.classes.test.ts
test/integration/dom.overlays.test.ts
test/integration/helpers/bpmn-visualization-initialization.ts
test/integration/jest.config.js

Create dedicated files for each kind of tests for clarity.
Configure mxGraph label generation during jest setup. This ensures that all tests have the right configuration (no more setup in test files).

[TEST] Split integration tests related to DOM checks

---

.eslintrc.js
package-lock.json
package.json
test/.eslintrc.js
test/e2e/helpers/visu/bpmn-page-utils.ts
test/integration/BpmnVisualization.test.ts
test/integration/helpers/bpmn-visualization-initialization.ts
test/integration/helpers/html-utils.ts
test/integration/mxGraph.model.bpmn.elements.test.ts
test/unit/component/mxgraph/renderer/StyleComputer.test.ts
test/unit/component/mxgraph/shape/render/BpmnCanvas.test.ts
test/unit/component/parser/json/BpmnJsonParser.edge.test.ts
test/unit/component/parser/json/BpmnJsonParser.event.test.ts
test/unit/component/parser/json/BpmnJsonParser.group.test.ts
test/unit/component/parser/json/BpmnJsonParser.label.bounds.test.ts
test/unit/component/parser/json/BpmnJsonParser.label.font.test.ts
test/unit/component/parser/json/BpmnJsonParser.label.test.ts
test/unit/component/parser/json/BpmnJsonParser.lane.test.ts
test/unit/component/parser/json/BpmnJsonParser.process.test.ts
test/unit/component/parser/json/BpmnJsonParser.sequenceFlow.conditional.test.ts
test/unit/component/parser/json/BpmnJsonParser.sequenceFlow.default.test.ts
test/unit/component/parser/json/BpmnJsonParser.sub.process.test.ts
test/unit/component/parser/json/TestUtils.ts
test/unit/component/parser/xml/BpmnXmlParser.bonita-community-2021_1.test.ts
test/unit/component/parser/xml/BpmnXmlParser.bpmn-plus-composer-v_10_4.test.ts
test/unit/component/parser/xml/BpmnXmlParser.omnitracker-bpmn-11_5.test.ts

Install the [`eslint-plugin-jest`](https://github.com/jest-community/eslint-plugin-jest) dependency to install ESLint Plugin Playwright in a future PR, to fix [`'page' is not defined`](https://github.com/playwright-community/jest-playwright#eslint-globals--page-is-not-defined).

[INFRA] Install the eslint-plugin-jest dependency 

---

package-lock.json
package.json
test/bundles/.eslintrc.js
test/e2e/.eslintrc.js
test/performance/.eslintrc.js

Install ESLint Plugin Playwright to fix [`'page' is not defined`](https://github.com/playwright-community/jest-playwright#eslint-globals--page-is-not-defined).

[INFRA] Install the ESLint Plugin Playwright dependency

---

.github/workflows/build.yml
.github/workflows/test-e2e.yml

To be sure that the browser is correctly installed in the GH: https://github.com/microsoft/playwright/issues/5801
Following recommandations:
- https://github.com/microsoft/playwright/issues/4033
- https://github.com/microsoft/playwright/issues/2539
- https://github.com/microsoft/playwright/issues/5767
- https://gkushang.medium.com/playwright-failed-to-launch-browsers-how-to-solve-8b01d03fe5b9

[INFRA] Fix the browser installation in the Github actions

---

test/performance/bpmn.navigation.performance.test.ts

Remove a unnecessary 'each' on a performance test

[TEST] Simplify the performance test

---

.github/workflows/dependency-review-pr.yml

See
- doc: https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/about-dependency-review#dependency-review-enforcement
- action: https://github.com/actions/dependency-review-action

[INFRA] Add a worfklow to review dependencies in PR

---

.github/workflows/publish-npm.yml

The event created by the new workflow will be used by https://github.com/process-analytics/bpmn-visualization-R/pull/34
Covers https://github.com/process-analytics/bpmn-visualization-R/issues/5

[INFRA] Notify the bpmn-visualization-R repository after NPM publish

---

NOTICE
package.json

This file is a companion of the LICENSE file.
Update the year with the current year in the NOTICE file.
To test locally, run `npm pack` and check the content of the generated tar.gz file

[INFRA] Include the NOTICE file in the npm package

---

.github/workflows/codeql-analysis.yml

It was not set as part of #2030 and not tested in the playground repository https://github.com/process-analytics/github-actions-playground/issues/30
I configured the permissions based on the [action README](https://github.com/github/codeql-action/tree/v2.1.12#usage)
The related called API that generates a 403 error is https://docs.github.com/en/rest/code-scanning#about-the-code-scanning-api
Example of 403 error with missing permissions in commit 2896487
https://github.com/process-analytics/bpmn-visualization-js/runs/6790500021?check_suite_focus=true#step:3:12
<details>
<summary>403 error in workflow run</summary>
<pre>
RequestError [HttpError]: Resource not accessible by integration
at /home/runner/work/_actions/github/codeql-action/v2/node_modules/@octokit/request/dist-node/index.js:66:23 …

[INFRA] Fix GH Token permissions for codeql analysis workflow

---

src/component/parser/json/BpmnJsonParser.ts
src/component/parser/json/converter/CategoryConverter.ts
src/component/parser/json/converter/CollaborationConverter.ts
src/component/parser/json/converter/ProcessConverter.ts
src/component/parser/json/converter/utils.ts
test/unit/component/parser/BpmnParser.test.ts
test/unit/component/parser/json/JsonTestUtils.ts

[REFACTOR] Apply some refactoring in ProcessConverter & JsonTestUtils

---

.github/workflows/generate-demo-preview.yml
.github/workflows/upload-demo-archive-and-trigger-examples-repository-update.yml
dev/public/overlays.html
scripts/prepare-demo-for-publish.mjs
vite.config.js

[INFRA] Fix the demo package: allow deploy on a non root context

---

README.md

Also improve the 'Features' list
Based on work initiated in #2184.

[DOC] Update browsers list in README

---

README.md

Reuse the image from the examples repository.

[DOC] Update the REAME hero image to promote Hacktoberfest

---

package.json

[INFRA] Update the keywords of the npm package

---

docs/contributors/maintainers.md

Add a step in the release process.
If this PR is approved, we should do the same in the R package repository: https://github.com/process-analytics/bpmn-visualization-R/blob/main/CONTRIBUTING.md#communicate-about-the-release

[DOC] Announce releases on Discord

---

docs/contributors/README.md
docs/contributors/bpmn-support-how-to.md

Add information about how to manage the BPMN element icons.
Name some sites that contributors can use to select an icon.

[DOC] Improve the BPMN support how-to

---

.github/actions/notify-PA-repo-of-new-version/action.yml
.github/workflows/publish-npm.yml
.github/workflows/upload-demo-archive-and-trigger-examples-repository-update.yml
README.md
dev/public/bpmn-rendering.html
dev/public/diagram-navigation.html
dev/public/elements-identification.html
dev/public/index.html
dev/public/lib-integration.html
dev/public/overlays.html
docs/contributors/maintainers.md
docs/contributors/mxgraph-version-bump.md
test/bundles/bundles.test.ts
test/bundles/static/lib-integration-iife.html
test/e2e/helpers/visu/bpmn-page-utils.ts

[REFACTOR] Update the lib name in the documentation and the demo

---

dev/public/index.html

fontawsome changelog for version 6.3.0: https://fontawesome.com/docs/changelog/#v6-3-0

[DEMO] Bump fontawesome from 6.2.1 to 6.3.0

---

.github/workflows/release.yml

Conform to `Conventional Commits`.
Not managed as part of #2529. Issue detected in 7ec1c068ae744089578f140303c1c93f162a9650.
Tested in https://github.com/process-analytics/github-actions-playground/pull/236#issuecomment-1456079369.

ci(release): improve the release commit message

---

test/integration/matchers/matcher-utils.ts
test/integration/matchers/toBeEdge/index.ts
test/integration/matchers/toBeShape/index.ts
test/integration/mxGraph.model.style.api.test.ts

Clarify the name of the properties related to the style. They now correspond exactly to their related counterpart in the mxGraph objects.
Rename utility functions to match the new name of the properties. The tests of the "Update Style" API can now fully use the utility functions as they also manage the style of the view state of the cell. So, this reduces the duplication.
Detected while implementing #2556.

test: simplify utility code in integration tests

---

dev/public/elements-identification.html

feat: add all BPMN Elements in Elements Identification page

---

src/component/parser/json/converter/ProcessConverter.ts

Generalize the processing of flow nodes elements.
There's no longer any need for special processing for `boundary events` and `transaction sub-processes`. This generalization prepares the support of adhoc sub-processes.
Covers #308 
This solution had been evaluated without success as part of #2296. It can now be done thanks to the implementation chosen in #2674.

refactor: simplify the parsing of elements of process

---

README.md

Also update the list of the bundles provided within the npm package.

docs: update browsers version in README

---

docs/users/overview.adoc

I have double check the wording with Deepl.

docs: improve paragraphs about colors and styles

---

dev/public/index.html

https://github.com/FortAwesome/Font-Awesome/releases/tag/6.4.2

chore(demo): bump fontawesome from 6.4.0 to 6.4.2

---

SECURITY.md

Same content as in https://github.com/process-analytics/bv-experimental-add-ons/pull/93 as agreed with @csouchet

docs: describe the security policy

---

src/component/options.ts

Specify that it has no effect on the navigation API.

docs: improve the JSDoc of `NavigationConfiguration.enabled`

---

.eslintrc.cjs
dev/ts/component/DropFileUserInterface.ts
dev/ts/component/ThemedBpmnVisualization.ts
dev/ts/pages/diagram-navigation.ts
dev/ts/pages/elements-identification.ts
dev/ts/pages/index.ts
scripts/prepare-demo-for-publish.mjs
src/component/mxgraph/BpmnRenderer.ts
src/component/mxgraph/config/StyleConfigurator.ts
src/component/mxgraph/overlay/updater.ts
src/component/mxgraph/renderer/style-utils.ts
src/component/mxgraph/shape/activity-shapes.ts
src/component/mxgraph/shape/render/utils.ts
src/component/parser/json/converter/CategoryConverter.ts
src/component/parser/json/converter/CollaborationConverter.ts
src/component/parser/json/converter/DiagramConverter.ts
src/component/parser/json/converter/EventDefinitionConverter.ts
src/component/parser/json/converter/GlobalTaskConverter.ts
src/component/parser/json/converter/ProcessConverter.ts
src/component/registry/bpmn-model-filters.ts
src/component/registry/bpmn-model-registry.ts
src/component/registry/css-registry.ts
test/unit/component/parser/json/BpmnJsonParser.event.test.ts
test/unit/component/parser/json/BpmnJsonParser.process.test.ts
test/unit/helpers/JsonBuilder.ts
test/unit/helpers/bpmn-model-utils.ts

To avoid to have to many changes by enabling `plugin:unicorn/recommended`, I choose to enable some rule one-by-one.
https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/no-array-for-each.md
Part of #2824
Covers #2742

chore(eslint): add `unicorn/no-array-for-each` rule

---

dev/public/index.html

v6.5.2 Changelog: https://fontawesome.com/docs/changelog/
Previous bump done in #2981.

chore(demo): bump fontawesome from 6.5.1 to 6.5.2

---

README.md

Also update the list of browsers that are known working with `bpmn-visualization` 0.43.0.

docs: advertise the `bv-addons` package in the README

---

dev/public/index.html

v6.6.0 Changelog: https://fontawesome.com/docs/changelog/
Previous bump done in #3070.

chore(demo): bump fontawesome from 6.5.2 to 6.6.0

---

dev/public/index.html

**Changelog**: https://fontawesome.com/changelog#v6-7-1

chore(demo): bump fontawesome 6.7.0 from to 6.7.1

---

dev/public/index.html

Changelog: https://fontawesome.com/changelog#v6-7-2

chore(demo): bump fontawesome 6.7.1 from to 6.7.2

---

docs/contributors/maintainers.md

Provide more details about:
- how to choose the new version
- managing the issues and the milestone
Based on https://github.com/process-analytics/bpmn-visualization-addons/pull/364

docs: improve the release how-to
